### ISSUE TITLE
(error "straight.el bootstrap failed: Wrong type argument: listp, \\.\\.\\.\n")

### ISSUE THREAD

**Issue by kqr** [raxod502/straight.el#450] opened 2019-12-30 19:58 UTC
## What's wrong

The specific error is not very informative, and as such has been truncated. There is more information on the specific problem below.

```
Debugger entered--Lisp error: (error "straight.el bootstrap failed: Wrong type argument: listp, \\.\\.\\.\n")
  signal(error ("straight.el bootstrap failed: Wrong type argument: listp, \\.\\.\\.\n"))
  error("straight.el bootstrap failed: %s" "Wrong type argument: listp, \\.\\.\\.\n")
  (if (= 0 (call-process (let ((emacs-binary-path (expand-file-name invocation-name invocation-directory)) (runemacs-binary-path (if (straight--windows-os-p) (progn ...)))) (if (and runemacs-binary-path (file-exists-p runemacs-binary-path)) runemacs-binary-path emacs-binary-path)) nil (quote (t t)) nil "--batch" "--no-window-system" "--quick" "--load" temp-file)) nil (error "straight.el bootstrap failed: %s" (buffer-string)))
```

This was caused by `print` in `install.el` abbreviating the printed object, i.e. the `temp-file` created by `install.el` ended with (yes, literally with the ellipses)

```
(progn (straight-use-package-no-build (\` (straight :type git :host github :repo ... :branch ...))) (unless (and (boundp ...) (integerp bootstrap-version) (>= bootstrap-version 3)) (let* (... ... ... ...) (ignore-errors ...) (if ... ... ...))))
```

My temporary workaround was to `(setq print-level nil)` before running the bootstrapping, but this could probably be let-bound as part of the `install.el` script. 

## Directions to reproduce

This did not happen on Linux, but did on macOS, using Yamamoto Mitsuharu's "Mac port", which is the best version of Emacs for macOS. It might very well be that this Mac port has a different default for print-level than regular Emacsen.

### Version information

* Emacs version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2019-12-30
* Operating system: macOS Mojave (10.14.6)

**Comment by kqr** [comment] 2019-12-30 20:39
Very surprisingly, the problem _might_ actually have been that I had tried tracking `straight/repos` in my overarching `.emacs.d` repository. 
This wasn't a problem until I pulled my configuration onto a different machine.

I realise now that this is probably not the intended usage, so I have tried untracking it by deleting everything in there and adding it to .gitignore in the root repository.
It looks like things are starting up better now,
but reinstalling all packages is taking some time so I don't know for sure yet.

**Comment by raxod502** [comment] 2020-01-02 00:53
`print-length` is the bane of my existence. Thanks for reporting the bug, should be fixed now.

**Comment by raxod502** [comment] 2020-01-02 00:54
Tracking the entire `repos` directory is indeed not the intended use case, but it is supported and should work just fine. I can't think of any reason why it would cause this problem, and if it does then that's almost certainly to be considered a bug in `straight.el` and not your fault.

**Comment by kqr** [comment] 2020-01-02 13:52
That was quick! Thanks.

Unfortunately, can't give you full technical details about how it failed when I was tracking `repos`, but what little I can tell you is that after having run `straight-pull-all` and answering yes/no to the best of my abilities to sensible-sounding questions about resetting remotes to their expected values, I ended up with my main .emacs.d repository being configured with a remote for a specific package in repos!

If you feel like trying to reproduce it, the commit it happened with is here: https://github.com/kqr/.emacs.d/commit/be09940c791f9d887dd04d65e0c5a66d0f55ab41

**Comment by raxod502** [comment] 2020-01-02 15:00
I have no idea how to reproduce that problem, but if I had to guess it would happen either because I forgot to bind `default-directory` somewhere, because a recipe with a nil `local-repo` got processed for VC operations somehow, or because there was some interference between the buffer-local binding of `default-directory` and the recursive edit workflow in the VC operations. (That last one seems the most likely to me, and is also the biggest pain to identify and fix.)

Is there anything else that needs to be done with the original issue in this thread?

**Comment by kqr** [comment] 2020-01-02 15:47
The issue represented by this ticked appears fixed. I have not had time to verify it, but it looks correct to me and this ticket can be closed as resolved as far as I'm concerned.

**Closed** 2020-01-02 17:30 UTC
Labels: bootstrap, bug, macos, waiting on response, ಠ_ಠ
