### ISSUE TITLE
:local-repo, tilde not expanded when cloning

### ISSUE THREAD

**Issue by noctuid** [raxod502/straight.el#339] opened 2018-12-29 17:19 UTC
Related to #133. `:local-repo "~/...".` works fine if the path already exists. If it does not, it fails to clone correctly unless an absolute path is specified instead.

Example:
```elisp
(straight-use-package
 '(el-patch
   :type git
   :host github
   :repo "noctuid/general.el"
   :local-repo "~/src/test/general"))
```

This results in an error that the directory does not exist (`"Setting current directory" "No such file or directory" "/home/noctuid/src/test/general/"`). The issue is that the tilde is expanded here but not when using `call-process` with `git`. The repo is actually cloned under `straight/repos/~/....`. I'm guessing it would make sense to use `expand-file-name` prior to calling `git`.

As a side note, would it be possible to use the default recipe for cloning if only `:local-repo` is specified?

**Comment by raxod502** [comment] 2018-12-30 00:51
Your bug should be fixed with the above commit; thanks for reporting it and correctly diagnosing the cause.

As for using the default recipe plus a custom `:local-repo`, I don't want to add _just_ that feature. Rather, I think some thought is needed to solve the problem in general. That idea is tracked in #116.

**Closed by raxod502** 2018-12-30 00:51 UTC
Labels: bug, custom local-repo, repository management

**Comment by noctuid** [comment] 2018-12-30 13:45
Thanks, it's working as expected now.

I was thinking mainly about it being useful for `:local-repo` and `:fork`, but consistent inheritance of keywords would be preferable of course. Thanks for pointing me to that issue.
