### ISSUE TITLE
Symbol's value as variable is void: comp-deferred-compilation-deny-list after a recent emacs commit

### ISSUE THREAD

**Issue by MintSoup** [raxod502/straight.el#763] opened 2021-05-17 10:49 UTC
[A recent emacs commit ](https://github.com/emacs-mirror/emacs/commit/8bc91a6a3f6cc84f549d24467832f67b3130201d#diff-33e02a4d29a78e1ab21694eaba92b1b59839106ffb711326a7b7e344a4706b07) renamed the variable `comp-deferred-compilation-deny-list` causing straight.el to break.

## Directions to reproduce

1. Build emacs from the latest branch.
2. Open emacs

**Comment by progfolio** [comment] 2021-05-17 11:04
Duplicate of #757

**Closed by progfolio** 2021-05-17 11:04 UTC
Labels: bug

**Comment by thierryvolpiatto** [comment] 2021-05-20 07:34
Because `comp-deferred-compilation-deny-list` don't exists anymore, now the new var is `native-comp-deferred-compilation-deny-list`.

```elisp
diff --git a/straight.el b/straight.el
index 3915e86..a810bfd 100644
--- a/straight.el
+++ b/straight.el
@@ -68,7 +68,7 @@ They are still logged to the *Messages* buffer.")))
 ;;;; Functions from other packages
 
 ;; `comp'
-(defvar comp-deferred-compilation-deny-list)
+(defvar native-comp-deferred-compilation-deny-list)
 
 ;; `finder-inf'
 (defvar package--builtins)
@@ -4827,7 +4827,7 @@ individual package recipe."
   "Predicate to check whether FILE should be native-compiled."
   (not (cl-some (lambda (re)
                   (string-match-p re file))
-                comp-deferred-compilation-deny-list)))
+                native-comp-deferred-compilation-deny-list)))
 
 
 (defun straight--build-native-compile (recipe)
@@ -4838,6 +4838,8 @@ repository. Also note that native compilation occurs
 asynchronously, and will continue in the background after
 `straight-use-package' returns."
   (when (and (fboundp 'native-compile-async)
+             (fboundp 'native-comp-available-p)
+             (native-comp-available-p)
              (member 'straight--build-compile straight--build-functions))
     (require 'comp)
     (straight--with-plist recipe (package)
@@ -4849,7 +4851,7 @@ asynchronously, and will continue in the background after
          'recursively nil
          #'straight--native-compile-file-p))
       ;; Prevent compilation of this package
-      (add-to-list 'comp-deferred-compilation-deny-list
+      (add-to-list 'native-comp-deferred-compilation-deny-list
                    (format "^%s" (straight--build-dir package))))))
 
 ;;;;; Info compilation
```

**Comment by progfolio** [comment] 2021-05-20 13:11
@thierryvolpiatto:
Thanks for the heads up. The variable name change should be accounted for already on the latest develop and master branch.
If that's not the case, we'll need to address that. Can you confirm that you are on the latest master or devel branch?
