### ISSUE TITLE
Poor performance when loading EAF (Emacs Application Framework)

### ISSUE THREAD

**Issue by iris-garcia** [raxod502/straight.el#769] opened 2021-05-25 07:35 UTC
Hi, I have recently updated straight to its latest version and also built Emacs from `master`:
- GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-24

And loading a package using straight takes 3.5 seconds (before it was less than 0.5)
```
(use-package eaf
  :straight (eaf :host github
                 :repo "manateelazycat/emacs-application-framework"
                 :branch "master"
                 :files ("*"))
  :defer 10
  :init
  (use-package epc :straight t :defer 10)
  (use-package ctable :straight t :defer 10)
  (use-package deferred :straight t :defer 10)
  (use-package s :straight t :defer 10)
  )
```

**Comment by progfolio** [comment] 2021-05-25 15:24
Hi Iris, I'm curious if this affects all packages on your end or just EAF?
Could you also please include the output of `M-x straight-version`?

**Comment by progfolio** [comment] 2021-05-25 15:34
Linking your related issue @ the EAF repo:

https://github.com/manateelazycat/emacs-application-framework/issues/678

**Comment by progfolio** [comment] 2021-05-25 17:12
I wrote this test to see where the issue lies. I had to modify the `:files` directive to include EAF's `app` folder, otherwise I got a loading error.


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "eaf-performance-test.straight"
  :preserve t
  :post-bootstrap 
  (let
      ((start
        (current-time)))
    (straight-use-package 's)
    (straight-use-package 'epc)
    (straight-use-package 'ctable)
    (straight-use-package 'deferred)
    (straight-use-package
     '(eaf :host github :repo "manateelazycat/emacs-application-framework" :branch "master" :files
           ("eaf-all-the-icons.el" "eaf-org.el" "eaf.el" "app")))
    (message "EAF initialized in %2.f seconds"
             (float-time
              (time-subtract
               (current-time)
               start)))
    (setq start
          (current-time))
    (require 'eaf)
    (message "EAF loaded in %2.f seconds"
             (float-time
              (time-subtract
               (current-time)
               start)))))
```
</details>

- Test run at: `2021-05-25 13:04:51`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) e46292d 2021-05-12`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-05-19`

<details><summary>Output</summary>

```emacs-lisp
Test run with version: prerelease (HEAD -> develop, origin/develop) e46292d 2021-05-12
EAF initialized in  0 seconds
Package cl is deprecated
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘incf’ is an obsolete alias (as of 27.1); use ‘cl-incf’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘assert’ is an obsolete alias (as of 27.1); use ‘cl-assert’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘incf’ is an obsolete alias (as of 27.1); use ‘cl-incf’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘incf’ is an obsolete alias (as of 27.1); use ‘cl-incf’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘return’ is an obsolete alias (as of 27.1); use ‘cl-return’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epc.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epcs.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epcs.el: Warning: ‘return’ is an obsolete alias (as of 27.1); use ‘cl-return’ instead.
../../../../../../tmp/eaf-performance-test.straight/straight/build/epc/epcs.el: Warning: ‘loop’ is an obsolete alias (as of 27.1); use ‘cl-loop’ instead.
42781

EAF loaded in 60 seconds
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 6cee0395 2021-05-25
"gnu-elpa-mirror"         n/a                  master 3f69bd0 2021-05-17
"el-get"                  melpa                master d76ac84a 2021-04-28
"emacsmirror-mirror"      n/a                  master ea0e522 2021-05-14
"straight"                n/a                  develop e46292d 2021-05-12
"s"                       melpa                master 3a5166c 2021-04-02
"epc"                     melpa                master e1bfa5c 2017-09-01
"concurrent"              melpa                master 2239671 2017-09-01
"deferred"                melpa                master 2239671 2017-09-01
"ctable"                  melpa                master 48b7374 2021-01-28
"eaf"                     emacsmirror-mirror   master cb0613d 2021-05-23


```
</details>

For me I was hitting a long load time when `straight-bug-report` was run non-interactively.
I tried running it through permutations of interactive/non-interactive with a fresh install vs a previous install:


<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">interactive?</th>
<th scope="col" class="org-left">fresh install?</th>
<th scope="col" class="org-right">initialized (seconds)</th>
<th scope="col" class="org-right">loaded (seconds)</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">t</td>
<td class="org-left">t</td>
<td class="org-right">7</td>
<td class="org-right">0</td>
</tr>


<tr>
<td class="org-left">t</td>
<td class="org-left">nil</td>
<td class="org-right">0</td>
<td class="org-right">0</td>
</tr>


<tr>
<td class="org-left">nil</td>
<td class="org-left">t</td>
<td class="org-right">7</td>
<td class="org-right">60</td>
</tr>


<tr>
<td class="org-left">nil</td>
<td class="org-left">nil</td>
<td class="org-right">0</td>
<td class="org-right">60</td>
</tr>
</tbody>
</table>


The initialization times with a fresh install are not surprising, as we have to install straight and all the packages.
However, the non-interactive case was a consistent 60 seconds to load regardless of whether or not the packages were previously installed.
I looked through `eaf.el` to see if I could find any hard-coded timers.
This is responsible for what I'm seeing:

<https://github.com/manateelazycat/emacs-application-framework/blob/cb0613dc070b646b756004acab9f380be031b9f4/eaf.el#L266-L269>

Otherwise there seems to be no loading delay.
Happy to look into this more if you can come up with a reproducible case, but I am unable to reproduce.

**Comment by iris-garcia** [comment] 2021-05-26 09:06
> Hi Iris, I'm curious if this affects all packages on your end or just EAF?
> Could you also please include the output of `M-x straight-version`?

straight-version: `prerelease (HEAD -> master, origin/master, origin/HEAD) 5541697 2021-05-19`

And regarding the other packages, it is weird it just happens with this package.

Also thanks a lot for the detailed debug information.

The only tests I have done is using `load-path` then `require 'eaf` which loads the package very fast (less than 0.5s).

**Comment by progfolio** [comment] 2021-05-26 12:37
You could run the profiler^1 around the code which loads EAF in both cases.
e.g.

(progn
  (require 'profiler)
  (profiler-start 'cpu+mem)
  (require 'eaf)
  (profiler-stop))

You can then obtain a report via `M-x profiler-report` to see where the time is being spent.
I would recommend doing this in both cases and seeing what differs.


Considering this only affects EAF and I am unable to reproduce, I think the issue either lies upstream or in your configuration.
I'll close this issue, but comment if you discover anything new and we can reopen if necessary.

[1](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html)

**Closed by progfolio** 2021-05-26 12:37 UTC
Labels: bug
