### ISSUE TITLE
Couldn't install on Windows

### ISSUE THREAD

**Issue by akork** [raxod502/straight.el#368] opened 2019-03-30 21:14 UTC
Installation failes with file missing error:
```
File is missing: Cannot open load file, No such file or directory, c:/Users/AK/AppData/Roaming/.emacs.d/straight/repos/straight.el/bootstrap.el
```  
Evaluation of this chunk
```
(with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp))
```
reports success
```
Bootstrapping straight.el...done
```
Directory `straight/repos/straight.el` is created but it's empty.

I'm using Emacs 26.1. Freshly installed by copying from gnu mirror.
What can it be?  Any permissions issue or something?

**Comment by raxod502** [comment] 2019-04-01 15:44
I'm not sure what could be wrong here. Unfortunately, I don't currently own any Windows systems, so it will be difficult for me to test this. Maybe someone who does use `straight.el` on Windows can chime in?

**Comment by priyadarshan** [comment] 2019-04-05 06:52
I will try to check over the week-end, if it can be of help, as I am trying to start using `straight.el` in my setup.

But one could also consider using Emacs on WSL as it runs perfectly fine, even smoother than native Windows. I will be back later with some results.

**Comment by priyadarshan** [comment] 2019-04-05 15:07
I just tested `straight.el` following the README, and I could have it up and running with no issues on Windows 10, having the directory you mentioned `straight/repos/straight.el` with the proper git repo. 

In my case, I have installed Emacs using scoop -g (for global), and it stits in c:\tools\emacs.

Sorry I could not be of much help.

**Comment by akork** [comment] 2019-04-07 14:49
Tested again and now it's loading files. Can't tell what was wrong, maybe system restart was needed.  I think we can close it.

**Comment by ujikol** [comment] 2020-04-10 08:36
I've the same issue. Could not be fixed by restart.

I verified:
- install.el was downloaded
- install.el executes without error, reporting "..done", returning t
- straight.el folder created
but bootstrap.el not does not exist

**Comment by raxod502** [comment] 2020-04-10 14:09
So the `~/.emacs.d/straight/repos/straight.el` directory exists but has no contents whatsoever, even the `.git` directory is missing? If the `.git` directory is there, what does Git say about the status?

**Comment by ujikol** [comment] 2020-04-10 14:14
There was no .git dir, afaicr.

Resolved by re-installing emacs, but then using the same unit.el.

Maybe caused by originally having used other means of package management???

Radon Rosborough <notifications@github.com> schrieb am Fr., 10. Apr. 2020,
16:09:

**Comment by raxod502** [comment] 2020-04-10 14:21
Very mysterious indeed.

**Comment by Igorek536** [comment] 2020-08-11 06:34
Same issue. Please reopen.

- Emacs version: 26.3
- OS: Windows 10

**Comment by raxod502** [comment] 2020-08-14 15:54
Sure, although unless somebody can trace the execution of the bootstrap process (which I cannot do, not being a Windows user), the issue is unlikely to be resolved.

**Comment by clockoon** [comment] 2020-11-03 13:53
In my case, I found that encoding error during `call-process` part in `install.el` is the problem. There might be some unicode characters that cannot be decoded in a default Windows Emacs environment. Forcing the utf-8 encoding for the bootstrap file will resolve the problem.

**Comment by raxod502** [comment] 2020-11-07 13:03
Oh, nice! Do you want to submit a pull request with that change? Looks like it would be pretty safe and a definite improvement for Windows users.

**Comment by clockoon** [comment] 2020-11-09 16:46
Of course, I will PR the commit.

**Comment by raxod502** [comment] 2020-11-13 15:22
The above pull request, now merged to develop, may fix this problem.

**Comment by raxod502** [comment] 2021-02-11 20:00
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)

**Closed by raxod502** 2021-02-11 20:00 UTC
Labels: bootstrap, bug, needs repro, waiting on response, windows
