### ISSUE TITLE
The autoload file path is something like "../../../../../.emacs.d/straight/build/company/company"

### ISSUE THREAD

**Issue by nasyxx** [raxod502/straight.el#701] opened 2021-02-25 22:32 UTC
## What's wrong

Today, when I open my emacs, some errors happened like:

```
Cannot open load file: No such file or directory, 
../../../../../.emacs.d/straight/build/nasy-tools/nasy-tools-company-function
```

When I searched for the reason, I found some file paths of the auto-generate autoloads files inside `straight/build/xx` is like `../../../../../.emacs.d/straight/build/xx`. E.g.:

```emacs-lisp
 (custom-autoload 'global-company-mode "../../../../../.emacs.d/straight/build/company/company" nil)

  (autoload 'global-company-mode "../../../../../.emacs.d/straight/build/company/company" "\
  Toggle Company mode in all buffers.
  With prefix ARG, enable Global Company mode if ARG is positive; otherwise,
  disable it.  If called from Lisp, enable the mode if ARG is omitted or nil.

  Company mode is enabled in all buffers where `company-mode-on' would do it.

  See `company-mode' for more information on Company mode.

  \(fn &optional ARG)" t nil)

  (autoload 'company-manual-begin "../../../../../.emacs.d/straight/build/company/company" nil t nil)
```

My `.emacs.d` is a soft link of `~/.config/nasy-emacs`.  When using the relative position of going to the parent folders and returning, it looks for `~/.config/.emacs.d/` instead of `~/.emacs.d/` or `~/.config/nasy-emacs/`

Currently, I use `gsed -i 's#../../../../../.emacs.d#/Users/Nasy/.emacs.d#g' stright/build/*/*.el` to do a temporary fixing.

**Is there any way to force it to generate an absolute path or a relative path without "../.."?**

## Directions to reproduce

For `"../../../../../.emacs.d/xxx"`, I am not sure what caused this to happen.  Some of them still keep `(autoload 'xx "xx")`.

And you could try:

```
git clone https://github.com/nasyxx/emacs.d.git ~/.config/nasy-emacs
ln -s $HOME/.config/nasy-emacs $HOME/.emacs.d
cd $HOME/.emacs.d/
make generate -j
emacs
```

### Version information

* Emacs version: emacsGit build with https://github.com/nix-community/emacs-overlay
* Operating system: macOS 11.2.1

**Comment by progfolio** [comment] 2021-02-26 01:47
What is the output of `M-x straight-version`?

**Comment by progfolio** [comment] 2021-02-26 01:57
If you could please provide the output of this as well (prior to applying your gsed workaround):

```emacs-lisp
(straight--autoloads-file "company")
```

**Comment by nasyxx** [comment] 2021-02-26 02:12
`M-x straight-version`

prerelease (grafted, HEAD -> develop, origin/develop) c94516d 2021-02-23

`(straight--autoloads-file "company")`

"/Users/Nasy/.emacs.d/straight/build/company/company-autoloads.el"

**Comment by nasyxx** [comment] 2021-03-10 03:30
Hi,

Sorry for that.  It should be work now.  I have updated the Makefile to generate it.

And about this issue.  I have some progress.

I notice that the nix-version emacs, build with an old macOS SDK.  It uses the 10.12 version.  I guess the old SDK may have issues with the new system (11.2) when I build emacs outside nix and use the latest SDK. This issue hasn't happened again.

**Comment by dylanjm** [comment] 2021-09-02 18:52
I'm actually having the same problem and can verify that specific packages are generating autoloads with a hardcoded path. I've had this problem for several months now, but it goes away when I switch back to Emacs 27 from Emacs 28.

**Comment by progfolio** [comment] 2021-09-02 19:15
It would be helpful if you could reproduce the problem via `straight-bug-report`.

**Comment by dylanjm** [comment] 2021-09-02 21:10
Okay, after narrowing down the problem it seems to me that there is an issue with `(setq find-file-visit-truename t)`. Similar to OP, I have my emacs symlinked from my dotfiles folder to `~/.config/emacs`. Here is the output of `straight-bug-report`. 


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :pre-bootstrap 
  (setq-default straight-repository-branch "develop")
  (setq-default straight-fix-org t)
  (setq-default straight-fix-flycheck t)
  (setq-default straight-use-package-by-default t)
  (setq-default straight-check-for-modifications
		'(check-on-save find-when-checking))
  :post-bootstrap 
  (setq-default use-package-verbose nil)
  (setq-default use-package-always-defer t)
  (setq-default use-package-compute-statistics nil)
  (setq-default use-package-expand-minimally t)
  (setq-default use-package-enable-imenu-support nil)
  (straight-use-package 'use-package)
  (use-package files :straight
    (:type built-in)
    :init
    (setq-default find-file-visit-truename t))
  (use-package editorconfig :straight t :hook
    (emacs-startup . editorconfig-mode))
  (message "bye"))
```
</details>

- Test run at: `2021-09-02 15:07:04`
- system-type: `darwin`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 45eb611 2021-08-13`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H1323))
 of 2021-09-02`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 45eb611 2021-08-13
Cloning use-package...
Cloning use-package...done
Building use-package...
Building use-package → Building bind-key...
Building use-package → Building bind-key...done
Building use-package...
Building use-package...done
Cloning editorconfig-emacs (for editorconfig)...
Cloning editorconfig-emacs (for editorconfig)...done
Building editorconfig...
Building editorconfig...done

bye
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master ed12df24 2021-08-30
"gnu-elpa-mirror"         n/a                  master a4cb567 2021-08-29
"el-get"                  melpa                master b5a5a405 2021-09-01
"emacsmirror-mirror"      n/a                  master fc970dc 2021-08-27
"straight"                n/a                  develop 45eb611 2021-08-13
"use-package"             melpa                master a7422fb 2021-02-10
"bind-key"                melpa                master a7422fb 2021-02-10
"editorconfig"            melpa                master 2ab86dc 2021-09-02


```
</details>

Here is also a pretty small `init.el` file that can be directly tested:

```emacs-lisp
;;; init.el --- Arco Emacs main configuration file -*- lexical-binding: t; -*-

(setq-default straight-repository-branch "develop"
                      straight-fix-org t
                      straight-fix-flycheck t
                      straight-use-package-by-default t
                      straight-check-for-modifications '(check-on-save find-when-checking))

(defvar bootstrap-version)
(let ((bootstrap-file
	   (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	  (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	    (url-retrieve-synchronously
	     "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	     'silent 'inhibit-cookies)
	  (goto-char (point-max))
	  (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq-default use-package-verbose nil
                      use-package-always-defer t
                      use-package-compute-statistics nil
                      use-package-expand-minimally t
                      use-package-enable-imenu-support nil)
(straight-use-package 'use-package)

(use-package files
  :straight (:type built-in)
  :init
  (setq-default find-file-visit-truename t))

(use-package editorconfig
  :straight t
  :hook (emacs-startup . editorconfig-mode))

(provide 'init)
  ;;; init.el ends here
```

**Comment by dylanjm** [comment] 2021-09-02 21:33
Okay here, I believe I have found a complete way to reproduce this. 

1. Save the above init-file to someplace like `~/dotfiles/emacs/init.el`
2. Run `ln -s ~/dotfiles/emacs ~/.emacs.d`
3. Run `emacs`

This will give the error `Cannot open load file` error. What's strange is, if you symlink just the `init.el` it won't cause a problem. But it doesn't seem to like when the entire directory is symlinked from somewhere else.

**Comment by dylanjm** [comment] 2021-09-02 21:42
Also, I can only reproduce this error on Emacs 28. I just tried downgrading to 27.2 and do not get an error when launching emacs.

**Comment by progfolio** [comment] 2021-09-16 21:17
Thanks for the additional info, @dylanjm.
This likely means something has changed in Emacs 28.

Looking through anything related to symlinks I see the following:

https://github.com/emacs-mirror/emacs/commit/657fe8b9d87dd17d9b50dd8e15bfd917c6c630b2

d18b1c8c7583b981d4f3d687e49e82250d51634f

d23723cfb24b87170f53ce615bff083ef2d7e76a

It looks like this may also be Mac specific. Not sure what the differences, if any, are on that OS.

**Comment by progfolio** [comment] 2021-12-08 00:13
I see someone emailed the Emacs dev thread about this, but it did not get a response. If either of you are still experiencing this issue, I would recommend joining in on that thread, as it may help the maintainers develop a solution.

https://lists.gnu.org/archive/html/emacs-devel/2021-11/msg00511.html

**Comment by jiacai2050** [comment] 2021-12-09 03:04
@progfolio I've CCed @larsmagne in latest [mail list](https://lists.gnu.org/archive/html/emacs-devel/2021-12/msg00780.html), Hope we can get this fixed in upcoming Emacs-28.

**Comment by croqaz** [comment] 2021-12-09 16:13
Hi all, this happens to me as well, on Arch linux, using emacs28-git from AUR.
You can check this Reddit thread where I was describing the issue: https://www.reddit.com/r/emacs/comments/rcg4r2/help_transitioning_to_emacs_28/
Somebody amazing left a comment and I ended up in this thread.

Please ask me anything.

**Comment by jiacai2050** [comment] 2021-12-10 06:45
@croqaz Could you file a bug via `report-emacs-bug` and post the link to [this mail thread](https://lists.gnu.org/archive/html/emacs-devel/2021-12/msg00842.html).

**Comment by progfolio** [comment] 2021-12-10 16:16
> @croqaz Could you file a bug via report-emacs-bug and post the link to this mail thread.

They needn't file a separate bug report. They can reply to the existing thread if they have new information to add.

**Comment by progfolio** [comment] 2021-12-20 02:26
Closing this issue for now. The upstream bug report shows the error is reproducible without straight.el. Unfortunately, it does not seem like it has received any attention from the maintainers. Anyone affected by this, I recommend you try the repro test provided here: https://lists.gnu.org/r/bug-gnu-emacs/2021-12/msg00376.html

If you can reproduce the error with that, it may be worth adding to that thread.

**Closed by progfolio** 2021-12-20 02:26 UTC
Labels: bug, needs repro, upstream, autoloading, symlink

**Comment by blaenk** [comment] 2022-04-09 11:10
I also ran into this on Windows with Emacs 28 just now (but not on Linux with Emacs 29.0). Uninstalling 28 and reinstalling 27.2 resolved it right away.

Note that the linked bug reporter mentions this workaround albeit for `package-install`:

> Currently I use this snippet to patch the issue up:
> 
> ```
> (defun faerryn-patch-package-find-file-visit-truename (oldfun &rest r)
>   (let ((find-file-visit-truename nil))
>     (apply oldfun r)))
> (advice-add #'package-install :around
>             #'faerryn-patch-package-find-file-visit-truename)
> ```

I imagine because it's `package-install` that directly/indirectly causes the autoload generation, when using the stock package manager.

Does anyone know if there's a similar `straight.el` function we can advise for now to temporarily unset `find-file-visit-truename` when autoload generation occurs, then re-activate it? It seems like doing so would work around the issue which would at least allow us to use straight.el + Emacs 28 + symlink `.emacs.d` while the maintainers figure out the issue.

**Comment by progfolio** [comment] 2022-04-09 14:05
> Does anyone know if there's a similar straight.el function we can advise for now to temporarily unset find-file-visit-truename when autoload generation occurs, then re-activate it?

https://github.com/raxod502/straight.el/blob/af5437f2afd00936c883124d6d3098721c2d306c/straight.el#L4979

However,  advising the function is not a good solution. That function should be patched to lexically bind find-file-visit-truename.  Pull requests welcome.

I would recommend bumping the linked Emacs bug report first.  This should be solved upstream.

**Comment by blaenk** [comment] 2022-04-10 01:09
Thank you @progfolio!

I suppose I'll try advising it just to see if that workaround works first.

> That function should be patched to lexically bind find-file-visit-truename. Pull requests welcome.

By this, do you mean that we should add `find-file-visit-truename` to the `let` binding list? Then its value would be `nil` if emacs 28, otherwise take the "outer"/global value? Or would we unconditionally set it to `nil`?

I am definitely happy and willing to bump that bug report but admittedly I have zero idea how to go about doing that. My understanding is that this is a mailing list, so if I subscribe to the mailing list now, I won't get that email since it already happened in the past, so how can I reply to it? It's been a long while since I worked with mailing lists. Would you be kind enough to share some directions?

It seems like I'm supposed to click on this button:

![image](https://user-images.githubusercontent.com/84680/162596767-d083dbee-383a-4930-bd4e-d8daa07646d7.png)

and then also add `52292@debbugs.gnu.org` to the `To:` field based on [this answer](https://emacs.stackexchange.com/questions/62745/how-do-i-make-a-public-reply-to-a-particular-post-in-an-emacs-bug-report).

**Comment by blaenk** [comment] 2022-04-10 01:14
I can confirm this workaround works:

```elisp
(defun my-patch-package-find-file-visit-truename (oldfun &rest r)
  (let ((find-file-visit-truename nil))
    (apply oldfun r)))

(advice-add #'straight--build-autoloads :around
            #'my-patch-package-find-file-visit-truename)
```

But I acknowledge you're saying that's not the ideal solution, so I'm also happy to both:

1. Contribute a PR for the "lexical binding" once I hear back from my earlier question and
2. Bump that bug report once I figure out how to do so

**Comment by progfolio** [comment] 2022-04-10 16:28
> By this, do you mean that we should add find-file-visit-truename to the let binding list? Then its value would be nil if emacs 28, otherwise take the "outer"/global value? Or would we unconditionally set it to nil?

Yes, that's the general idea. Hopefully, we can unconditionally bind `find-file-visit-truename` to nil here:

https://github.com/raxod502/straight.el/blob/e2de88ea0e7ccf9f4846e9e756f86e0dcf469c44/straight.el#L5038-L5053

I'll have to do some testing/research to see if this is OK for versions prior to 28, or if we need to condition the value on that version.

Let's hold on that part for now and focus on getting this bug fixed upstream first.

You have the correct idea about replying to that bug. Especially the part about manually adding 52292@debbugs.gnu.org as a recipient.
You can put a note in your message that mentions you're not subscribed to the mailing list and to please CC you.

Thank you for taking this on.

**Comment by blaenk** [comment] 2022-04-10 23:36
Thank you! I did post a reply/bump yesterday, I think/hope I did it correctly:

https://lists.gnu.org/r/bug-gnu-emacs/2022-04/msg00444.html

I also subscribed to the mailing list just now.

**Comment by blaenk** [comment] 2022-04-10 23:49
As a further note for myself, I just learned [here](https://www.emacswiki.org/emacs/EmacsBugTracker) that the bug report is visible [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=52292) as well, and [here](https://issues.guix.gnu.org/issue/52292).

Also added some of this information to that same [wiki page](https://www.emacswiki.org/emacs/EmacsBugTracker#h5o-3). I'm not sure what "official" affiliation it has with emacs, if any (I doubt it does), but figured I'd add it there since it came up high in Google search results.

**Comment by shamindras** [comment] 2022-06-20 16:07
Hi all - I'm experiencing a similar issue. Note this is a cross-post from my stackexchange. 
**Note:** I'm posting here, because all comments point back to this thread, and my SE question is still not resolved.

I'm running emacs (v28.1) on my macOS (Montery v12.2.1) and I get the following message when trying to use `magit`:

```bash
command-execute: Cannot open load file: No such file or directory, ../../../../../../../.emacs.d/straight/build/magit/magit-status
```

My init file is [here](https://github.com/shamindras/ss_dotfiles/blob/main/.emacs.d/myinit.el). Importantly I have  my `~/.emacs.d` is **symlinked** to my dropbox folder:

```bash
.emacs.d -> ~/DROPBOX/REPOS/ss_dotfiles/.emacs.d
```

I tried the following suggested workarounds:

- @kisaragi-hiu in #944 in my init file [here](https://github.com/shamindras/ss_dotfiles/blob/main/.emacs.d/myinit.el#L126)
- @blaenk in [this patch](https://github.com/blaenk/dots/commit/4bb0880f5a1a5dc6f772a0bec1d1853c344738d2) in my init file [here](https://github.com/shamindras/ss_dotfiles/blob/main/.emacs.d/myinit.el#L128-L133)

Neither of these workarounds fix this issue with `straight.el` loading `projectile.el`. I've tried restarting emacs, the macOS etc, but the same problem persists.

@blaenk @progfolio @kisaragi-hiu - based on my init file, am I implementing your suggestions correctly?

**Comment by croqaz** [comment] 2022-06-21 09:01
Hi all, I also have the exact same problem with Emacs stable 28.1 on Arch.
I installed go-mode and I'm seeing the exact same error as above.
I eventually deleted the `~/.emacs.default/straight/build` folder and restarted Emacs and now it's working, after straight + Emacs rebuilt all the repos.

**Comment by shamindras** [comment] 2022-06-22 18:28
> I eventually deleted the `~/.emacs.default/straight/build` folder and restarted Emacs and now it's working, after straight + Emacs rebuilt all the repos.

@croqaz - that worked! Many thanks.

To be more precise I did the following:
1. Backup `~/.emacs.d` dir
2. Deleted the entire `~/.emacs.d/straight` dir. 
  - This is more than what @croqaz suggested, but I just wanted to be quite cautious to resolve this issue.
  - Re-installing everything from scratch took less than a minute for me. Thanks to `straight.el` 👍🏾 
4. Ensure that `(setq find-file-visit-truename nil)` is included in my [init file](https://github.com/shamindras/ss_dotfiles/blob/0bd4566b75df0c04610099cbafe946659fe11d86/.emacs.d/myinit.el?rgh-link-date=2022-06-20T16%3A07%3A00Z#L131) [after bootstrapping](https://github.com/shamindras/ss_dotfiles/blob/main/.emacs.d/myinit.el#L117-L129) `straight.el`.
5. Do a quick search for `setq find-file-visit-truename` and check that we have set it to `nil` and not `t` anywhere else.   - 
    - I had it set to `t` in my `dired`, which I removed. 
    - This did cause me issues, but were resolved after removing it and setting it to `nil` only once as per above.
