### ISSUE TITLE
Upstream seems to be checked out even when :fork is provided in the recipe.

### ISSUE THREAD

**Issue by Fuco1** [raxod502/straight.el#350] opened 2019-02-02 18:31 UTC
I have this recipe in my init

```elisp
(helm :repo "git@github.com:emacs-helm/helm.git" :remote "upstream"
      :fork (:repo "git@github.com:Fuco1/helm.git" :remote "origin"))
```

Yet after installation master is still checked out to upstream/master. This is wrong in my opinion. How can I force straight.el to always use my fork's master as the default checkout?

**Comment by raxod502** [comment] 2019-02-09 22:16
Should be fixed now. Thanks for the report! I never ran into it because I never used a branch on my fork that was also present in upstream.

**Comment by Fuco1** [comment] 2019-02-10 10:41
I can confirm that the correct commit is checked out but it is in a detached head form.  So I still get the `fork/master` checked out but not a local tracking branch.

I'm not sure if that's relevant to this issue or another one should be opened.  

What I did to test this was pull latest straight.el, rebuld and reload, then delete the helm repo so a new clone would trigger.

**Comment by Fuco1** [comment] 2019-02-10 10:43
Actually, now I tried to create a branch and I got "branch master already exists", so I think it is still tracking the origin (upstream).

Personally I would prefer it to track the fork as I always sync with the upstream manually and push to my fork.

**Comment by raxod502** [comment] 2019-02-10 23:22
Can't reproduce. Running this code from an empty `~/.emacs.d`:

```elisp
(setq straight-repository-branch "develop")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package
 '(helm :repo "git@github.com:emacs-helm/helm.git" :remote "upstream"
        :fork (:repo "git@github.com:Fuco1/helm.git" :remote "origin")))

(let ((default-directory (straight--repos-dir "helm")))
  (compile "git status"))
```

gives me the following:

```
On branch master
Your branch is up to date with 'origin/master'.
```

Of course, if you have a version lockfile then the particular commit specified therein will be checked out, rather than the branch you specify in your recipe. Is that what is going on?

**Comment by Fuco1** [comment] 2019-02-10 23:32
Yes indeed, I have a lock file.

I think we can close!

**Comment by raxod502** [comment] 2019-02-11 03:10
Great. See also #66 to change the UX around detached HEADs.

**Closed by raxod502** 2019-02-11 03:10 UTC
Labels: bug, critical, fork, recipe-handling, waiting on response
