### ISSUE TITLE
Weird behavior with Emacs 27

### ISSUE THREAD

**Issue by nanounanue** [raxod502/straight.el#431] opened 2019-11-04 17:11 UTC
Just updated yesterday to GNU/Emacs 27 (`GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) of 2019-11-03`) and some packages are failing, in particular, in the step of building from the source they crash Emacs (this same config file works perfectly in other machines)

(The packages are `ess`, `paredit`)

Also `tramp` is not being compiled correctly, if:

```
Debugger entered--Lisp error: (invalid-function "((tramp-compat-with-mutex))")
  signal(invalid-function ("((tramp-compat-with-mutex))"))
  tramp-signal-hook-function(invalid-function ("(tramp-compat-with-mutex)"))
  signal(invalid-function ("(tramp-compat-with-mutex)"))
  tramp-maybe-open-connection((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("stafford-beer" 0 13 (tramp-default t)) nil "" nil))
  tramp-send-command((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("stafford-beer" 0 13 (tramp-default t)) nil "" nil) #("cd ~root && pwd" 4 8 (tramp-default t)))
  tramp-sh-handle-expand-file-name("/sudo::" nil)
  apply(tramp-sh-handle-expand-file-name ("/sudo::" nil))
  tramp-sh-file-name-handler(expand-file-name "/sudo::" nil)
  apply(tramp-sh-file-name-handler expand-file-name ("/sudo::" nil))
  tramp-file-name-handler(expand-file-name "/sudo::" nil)
  expand-file-name("/sudo::" nil)
  apply(expand-file-name ("/sudo::" nil))
  tramp-autoload-file-name-handler(expand-file-name "/sudo::" nil)
  expand-file-name("/sudo::")
  org-babel-execute-src-block(nil ("shell" "apt install html2text" ((:colname-names) (:rowname-names) (:result-params "silent") (:result-type . value) (:results . "silent") (:exports . "code") (:dir . "/sudo::") (:tangle . "no") (:comments . "org") (:eval . "no-export") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 2493 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

How can I fix it? Or how can I debug this?

**Comment by raxod502** [comment] 2019-11-08 17:32
I cannot reproduce the behavior. I pulled down the latest Emacs build from `silex/emacs:master` (i.e. using Docker), which is a build of 2019-11-04, and pasted in the bootstrap snippet followed by

```elisp
(straight-use-package 'ess)
(straight-use-package 'paredit)
```

(I also had to `apt install git` in an `*ansi-term*` to install Git inside the container.)

Can you construct some directions to reproduce the problem starting from an empty `~/.emacs.d`?

**Comment by nanounanue** [comment] 2019-11-11 03:05
Apparently this problem was related that I had a missing `'` in the following snippet:

```emacs-lisp
(use-package racket-mode
  :mode ("\\.rkt\\'" . racket-mode)
  ...
```

(the one before the final double quote)

The problem that persists is the one with `tramp` you can reproduce it in `org-mode` as follows:

```org-mode
#+begin_src shell :dir /sudo::
apt update  # or any other command, even ls
#+end_src
```

If you do `C-c C-c` to evaluate the block, you get
```
Debugger entered--Lisp error: (invalid-function "((tramp-compat-with-mutex))")
  signal(invalid-function ("((tramp-compat-with-mutex))"))
  tramp-signal-hook-function(invalid-function ("(tramp-compat-with-mutex)"))
  signal(invalid-function ("(tramp-compat-with-mutex)"))
  tramp-maybe-open-connection((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("stafford-beer" 0 13 (tramp-default t)) nil "" nil))
  tramp-send-command((tramp-file-name "sudo" #("root" 0 4 (tramp-default t)) nil #("stafford-beer" 0 13 (tramp-default t)) nil "" nil) #("cd ~root && pwd" 4 8 (tramp-default t)))
  tramp-sh-handle-expand-file-name("/sudo::" nil)
  apply(tramp-sh-handle-expand-file-name ("/sudo::" nil))
  tramp-sh-file-name-handler(expand-file-name "/sudo::" nil)
  apply(tramp-sh-file-name-handler expand-file-name ("/sudo::" nil))
  tramp-file-name-handler(expand-file-name "/sudo::" nil)
  expand-file-name("/sudo::")
  org-babel-execute-src-block(nil ("shell" "apt update  # or any other command, even ls" ((:colname-names) (:rowname-names) (:result-params "silent") (:result-type . value) (:results . "silent") (:exports . "code") (:dir . "/sudo::") (:tangle . "no") (:comments . "org") (:eval . "no-export") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 870 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

**Comment by raxod502** [comment] 2019-11-11 16:34
Intriguing. I guess TRAMP has some slightly less robust error handling for malformed regexps in the `auto-mode-alist`. Anyway, it seems to me like this problem doesn't have anything to do with `straight.el`. Is that right?

**Comment by yantar92** [comment] 2019-11-18 08:36
I also got emacs crashing during building/rebuilding packages. 

GDB output: 
```
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from emacs...
(gdb) run
Starting program: /usr/bin/emacs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff2b20700 (LWP 7546)]
[Detaching after vfork from child process 7577]
[Detaching after vfork from child process 7578]
[Detaching after vfork from child process 7616]
[Detaching after vfork from child process 7619]
[Detaching after vfork from child process 7620]
[Detaching after vfork from child process 7639]
[Detaching after vfork from child process 7668]
[Detaching after vfork from child process 7728]
[Detaching after vfork from child process 7729]
[Detaching after vfork from child process 7742]
[Detaching after vfork from child process 7825]
[Detaching after vfork from child process 7826]
[Detaching after vfork from child process 7855]
[Detaching after vfork from child process 7857]
[Detaching after vfork from child process 7858]
[Detaching after vfork from child process 7859]
[Detaching after vfork from child process 7860]
[Detaching after vfork from child process 8327]
[Detaching after vfork from child process 8328]
[Detaching after vfork from child process 8331]
[Detaching after vfork from child process 8332]
[Detaching after vfork from child process 8342]
[Detaching after vfork from child process 8343]
[Detaching after vfork from child process 8344]
[Detaching after vfork from child process 8345]
[Detaching after vfork from child process 8346]
[Detaching after vfork from child process 8347]
[Detaching after vfork from child process 8393]
[Detaching after vfork from child process 8394]
[Detaching after vfork from child process 8395]
[Thread 0x7ffff2b20700 (LWP 7546) exited]
[Inferior 1 (process 7522) exited with code 0377]
(gdb) bt
No stack.
(gdb) quit
```

Strangely, `debug-on-entry` on `straight-use-package` and step-by-step execution did not result in crashing.

After bisecting my init file, I have found a more precise condition when the bug appears.
The minimum working init file to reproduce the crash is below. The crash is triggered on `M-x straight-rebuild-package RET straight RET`.
````
(eval-and-compile
  (defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage)))

(eval-and-compile (straight-use-package 'use-package))

(use-package highlight-stages
  :straight t
  :hook emacs-lisp-mode)
(setq debug-on-error t)
````
Note that `:hook emacs-lisp-mode` throws an error on init ("Autoloading file ~/.emacs.d/straight/build/highlight-stages/highlight-stages.el failed to define function highlight-stages") because use-package attempts to run `highlight-stages` instead of `highlight-stages-mode`. Without this error, the crash disappears. 
Unsetting debug-on-error also makes the crash disappear.

**Comment by raxod502** [comment] 2019-11-18 16:29
Well, I can reproduce that from Docker. It is perplexing.

In the past, I've gotten the behavior of Emacs crashing only when `debug-on-error` was set in the case of a variable being lexically bound, then having another file be loaded which defined that variable as dynamically bound. The issue is that when Emacs byte-compiles, it sometimes makes assumptions about the validity of the code, and removes runtime checks which prevent crashes.

**Comment by yantar92** [comment] 2019-11-19 02:40
I managed to debug it a little deeper. The crash appears to happen while running `straight--generate-package-autoloads`. I managed to run everything until `let` and the first `let` binding (`generated-autoload-file`). The crash happens when attempting to set `noninteractive` to `t`. I tried to modify the function setting `noninteractive` to `nil` instead. The crash disappears.

**Comment by yantar92** [comment] 2019-11-19 02:45
Ok... It seems to be emacs bug, unless I misunderstand something in manual.

Running `emacs -Q` and evaluating the following code terminates emacs.
````
(setq debug-on-error t)
(let ((noninteractive t))
  (/ 1 0))
````

**Comment by raxod502** [comment] 2019-11-19 16:16
Oh. Well, that's embarrassing. Sounds like a mailing list inquiry.

Since `package-generate-autoloads` also binds `noninteractive` to `t`, does that mean `package.el` also now crashes if there's an error during autoloads generation?

**Comment by yantar92** [comment] 2019-11-19 17:00
I have sent a bug report. See https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-11/msg01379.html

**Comment by yantar92** [comment] 2019-11-20 16:33
Forwarding the reply from Eli Zaretskii on the issue:

>    > Note that package.el, for example, can set noninteractive to 't at some 
>    > point (see package-generate-autoloads), even if emacs is otherwise
>    > interactive. 
>    > 
>    > > Why are you binding noninteractive to t while debug-on-error is
>    > > enabled?
>    > 
>    > Similar to package.el, straight.el also binds noninteractive to 't when
>    > generating autoloads.
> 
>    What package.el does makes little sense to me, see below.  Does
>    straight.el have a reason to do the same, you did you just copy the
>    code from package.el?
> 
>    If the code in straight.el is simply a copy from package.el, then just
>    remove the line which binds 'noninteractive'.  You don't need it
>    because all it does is disable calls to 'message' inside
>    'autoload-generate-file-autoloads', and you already bind
>    'inhibit-message' to t, so no messages will be displayed anyway.
>

**Comment by raxod502** [comment] 2019-11-21 16:44
That's kinda silly, but okay. I removed `noninteractive` from `straight.el` so the issue should(?) be fixed now. Thanks so much for your help in determining the cause!

**Comment by yantar92** [comment] 2019-11-22 11:58
Seems to be fixed for me

**Comment by raxod502** [comment] 2020-02-20 12:31
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)

**Closed by raxod502** 2020-02-20 12:31 UTC
Labels: bug, build system, byte compilation, crash, startup, upstream, waiting on response, ಠ_ಠ
