### ISSUE TITLE
native-comp-deferred-compilation-deny-list void variable

### ISSUE THREAD

**Issue by iris-garcia** [raxod502/straight.el#767] opened 2021-05-24 09:58 UTC
## What's wrong
```
Debugger entered--Lisp error: (void-variable native-comp-deferred-compilation-deny-list)
  straight--build-native-compile((:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el"))
```

## Info
Just cloned emacs and switched to branch feature/native-comp
then tried to install straight:
```
(setq straight-use-package-by-default nil)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
```
And got the error:
```
Debugger entered--Lisp error: (void-variable native-comp-deferred-compilation-deny-list)
  straight--build-native-compile((:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el"))
  straight--build-package((:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el") nil)
  #f(compiled-function () #<bytecode -0x11b33a83c9fbf764>)()
  straight--transaction-exec(use-package-\(:type\ git\ :host\ github\ :repo\ \"raxod502/straight\.el\"\ :files\ \(\"straight*\.el\"\)\ :branch\ \"master\"\ :package\ \"straight\"\ :local-repo\ \"straight\.el\"\)-nil-nil :now #f(compiled-function () #<bytecode -0x11b33a83c9fbf764>))
  straight-use-package((straight :type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "master"))
  load-with-code-conversion("/home/igarcia/.emacs.d/straight/repos/straight.el/..." "/home/igarcia/.emacs.d/straight/repos/straight.el/..." nil t)
  load("/home/igarcia/.emacs.d/straight/repos/straight.el/..." nil nomessage)
  (let ((bootstrap-file (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory)) (bootstrap-version 5)) (if (file-exists-p bootstrap-file) nil (save-current-buffer (set-buffer (url-retrieve-synchronously "https://raw.githubusercontent.com/raxod502/straigh..." 'silent 'inhibit-cookies)) (goto-char (point-max)) (eval-print-last-sexp))) (load bootstrap-file nil 'nomessage))
  load-with-code-conversion("/home/igarcia/.emacs.d/init.el" "/home/igarcia/.emacs.d/init.el" t t)
  load("/home/igarcia/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x14492333506a56e6>) #f(compiled-function () #<bytecode -0x1f3c686ddc0cc375>) t)
  command-line()
  normal-top-level()

**Comment by progfolio** [comment] 2021-05-24 12:22
> Just cloned emacs and switched to branch feature/native-comp

That branch was merged into master. You should be building off of master with the `--with-native-compilation` option.

The bug you are seeing is due to an upstream change. 
Duplicate of #757

**Closed by progfolio** 2021-05-24 12:22 UTC
Labels: bug
