### ISSUE TITLE
Should the mirrors be version-locked?

### ISSUE THREAD

**Issue by ThibautVerron** [raxod502/straight.el#544] opened 2020-07-16 11:09 UTC
Hi,

Currently, when freezing the installed packages, the freeze includes the mirror repositories. 

It's not by itself a problem, but it makes it easy to reach a broken state, for example by installing a package which is only provided in a more recent version of the repo, and forgetting to update the version lock file. Then Emacs will start all right for the time being, but the next time we do a full install, it will fail to find the package. (It's approximate, don't take it as a full recipe.)

My question is, is there a good reason to version-lock those "fake" packages along with the rest?

**Comment by raxod502** [comment] 2020-07-16 12:52
![image](https://user-images.githubusercontent.com/6559064/87672643-83188000-c730-11ea-8e3e-83514411e40b.png)

_Everything_ should be locked. Otherwise we do not have reproducibility. What if a package is added to one of the mirror repositories and it shadows the version of that package you were previously using from another source? Then your config will break unexpectedly on a fresh install, because the latest version of the mirror repository was used.

In general, a configuration should not be considered reproducible unless the lockfile has been written. I hope that future work can make the workflow of updating and using a lockfile simpler and faster, so that it feels like less of a burden and is therefore easier to remember.

**Comment by ThibautVerron** [comment] 2020-07-16 14:37
Thanks for the very clear answer.

> What if a package is added to one of the mirror repositories and it shadows the version of that package you were previously using from another source? 

How could that happen exactly? At the very least packages which are locked to a commit should be safe: commit hashes should in principle not collide between different packages.

I imagine that packages which are locked by tags are more dangerous, but it should still be a rare occurrence.

Okay, fair enough. But somehow it doesn't feel like the more optimal and intuitive solution.

Another possibility would be to store the recipes in the lock file, maybe. Then a package would be locked to a specific source, and the reproducibility would be ensured regardless of whether the mirror version is more recent or older than the recipe.

> In general, a configuration should not be considered reproducible unless the lockfile has been written.

In my opinion there are two levels of reproducibility at play here. One is a developer trying to find and fix a bug. There you have a specific non-working situation and you want to reproduce it exactly. Current lockfiles are a very appropriate tool for that.

The other, and I'd wager more common, one is a user trying to clone his configuration. There he has a working configuration, and he doesn't care that much if the clone is exact, as long as it still works. And if it doesn't, he can just identify the problem package and lock it to a working version. For that use-case, lockfiles are not particularly convenient, if usable at all (can you lock a single package?). 

And regardless, for the non-tech-savvy user, lockfiles are probably scary -- for example, they have all those questions about version control tools in case straight things that a package was modified.

> I hope that future work can make the workflow of updating and using a lockfile simpler and faster, so that it feels like less of a burden and is therefore easier to remember.

That would be great. :)

But I don't know if it will ever be possible to get a lockfile system for both categories of users.

In the meantime, maybe it would be possible to implement a _more_ annoying system, by requiring that the cached recipes are provided by one of the repos, thus ensuring an earlier failure in most cases?

**Comment by raxod502** [comment] 2020-07-17 15:34
> How could that happen exactly? At the very least packages which are locked to a commit should be safe: commit hashes should in principle not collide between different packages.

Sometimes two different versions of a package, with totally unrelated version histories, are provided from two different sources. In that case if the package is cloned from the wrong source, `straight.el` will be unable to check out the locked commit and falls back to checking out the main branch.

> packages which are locked by tags

These do not yet exist, see #31 and #452.

> Another possibility would be to store the recipes in the lock file, maybe.

I'm of the opinion that this is a workaround rather than a proper solution. The fundamental issue is that lockfiles are awkward to use, hence it is easy to end up in a situation where you don't actually save a lockfile, hence your configuration doesn't work as expected. The proper solution is to make lockfiles easier, not try to make the system work even in the absence of proper lockfile usage. Think NPM/Yarn: if you don't use a lockfile and then complain about anything related to package versions, your issue will be ignored because you just should have used a lockfile. `straight.el` doesn't yet have a clean enough implementation to be there, but I'd like it to.

> can you lock a single package?

But why? What use case would this serve?

> for example, they have all those questions about version control tools in case straight thinks that a package was modified.

This is indeed a problem, and in my opinion it can be easily solved by adding an option to have `straight.el` just hard-reset all packages automatically. Users who want local changes to be preserved can disable this option, but users who don't do any package development can be shielded from the unnecessary complexity.

> But I don't know if it will ever be possible to get a lockfile system for both categories of users.

If a lockfile can be configured to be written automatically and noninteractively every time you run a package management command, then the user interface would be the same as `package.el`. Do you think this would suffice?

> requiring that the cached recipes are provided by one of the repos

Could you clarify what you mean by "cached recipes"? `straight.el` has a recipe cache, but it is transient and invalidated whenever the underlying recipe repository is changed at all, and so this system cannot possibly change any user-visible behavior.

**Comment by ThibautVerron** [comment] 2020-07-17 16:22
> if the package is cloned from the wrong source, straight.el will be unable to check out the locked commit and falls back to checking out the main branch.

Wow.

Then even with a lock file, you don't get a fully reproducible configuration, right? If a repository is deleted and recreated, straight will load whatever is on master? I don't think full reproducibility is achievable when you depend on data from the internet, but I think I would expect the system to fail to install the package in such case, rather than install an unknown version.

> The proper solution is to make lockfiles easier, not try to make the system work even in the absence of proper lockfile usage.

Okay. I'm more and more thinking that maybe my misunderstanding comes from the name "lockfile". To "freeze" or "lock" package versions, sounds like it means that you will need to unfreeze or unlock before you can update, so to me it sounds like a feature for users who do not want to update their packages too often. Not like a feature which is absolutely necessary for the system to work.

I'm not even doing regular package updates, but I am freezing my versions only when I'm absolutely sure that I want to save that configuration. It is a lot less often than I actually reproduce my configuration.

> This is indeed a problem, and in my opinion it can be easily solved by adding an option to have straight.el just hard-reset all packages automatically. Users who want local changes to be preserved can disable this option, but users who don't do any package development can be shielded from the unnecessary complexity.

I believe that you are right, but as a user who does tweak some packages sometimes but still more often accidentally changes source code when following `*help*` links, I would still be bitten by this approach. I have vaguely toyed with the idea of adding a dir-local variable forcing files in the repos directory to be visited as read only, but... I've been lazy so far.`:)`

Incidentally, I might be missing something, but I don't find straight to be particularly helpful for package development. It only removes a tiny part of the development phase, but all the forking and filing a pull request remain in place, and one has to set remotes by hand. So more often than not I just fork, clone the fork in another folder and tell straight to use the local copy. Anyway, not really the topic here.

> But why? What use case would this serve?

The one I described just above. Say, if I have a working configuration which requires that package `foo` is kept at its current version, but I like to have regular updates for other packages. Basically, the same use case as `package-load-list`.

I don't see an easy way to do it with the current all-or-nothing lockfiles. Maybe it is possible to specify a commit in the straight recipe (even if it comes from a recipe repository), but it's not as straightforward as calling a hypothetical `straight-freeze-single-package`.

And anyway, even if such a function existed, I don't see a clear way how both locks would cohabitate.

> If a lockfile can be configured to be written automatically and noninteractively every time you run a package management command, then the user interface would be the same as package.el. Do you think this would suffice?

That would indeed be a huge step in the right direction. But that would also require maintaining a history of lockfiles, in order to make sure that broken updates can be reverted, and then also implementing an interface to that history... 

> Could you clarify what you mean by "cached recipes"?

I meant whatever makes sure that if I do, for example, `straight-pull-package melpa` then `straight-use-package foo` for a package foo which was not in the locked version of the melpa mirror, and then I add `(use-package foo)` to my init file and restart emacs, then straight is still able to load the package. But I guess in this case it is that it doesn't care about the recipe if the package is already built?

**Comment by raxod502** [comment] 2020-07-18 12:57
> I think I would expect the system to fail to install the package in such case, rather than install an unknown version.

See #85. Of course, a warning is generated when this occurs.

> To "freeze" or "lock" package versions, sounds like it means that you will need to unfreeze or unlock before you can update, so to me it sounds like a feature for users who do not want to update their packages too often. Not like a feature which is absolutely necessary for the system to work.

As you suggest, this is completely wrong. I would be happy to hear any ideas about how to improve the documentation or nomenclature such that this is less confusing. The reason I selected the term _lockfile_ is that other package managers such as Yarn, RubyGems, Poetry, etc. use the word in the same way as `straight.el`.

> tell straight to use the local copy

Well, you can hardly say `straight.el` is not helping, no? Doing it without `straight.el` would require you to manually add to the load path, generate autoloads, byte-compile, and remember to do that all again every time you make a change. Also you'd be in hot water if working with a package that uses a nontrivial `:files` directive in its MELPA recipe.

> one has to set remotes by hand

You can specify `(straight-use-package '(el-patch :fork (:repo "my-name/el-patch")))` and `straight.el` will do this automatically (plus validate that they _stay_ correct, offer to push changes to your fork, etc.), although the UX could be improved.

> Say, if I have a working configuration which requires that package foo is kept at its current version, but I like to have regular updates for other packages.

Ah. Yes, this is a perfectly good use case, but it's not what a lockfile is for. You want to _pin_ a package. In Yarn, you would accomplish this by editing `package.json`, not by generating `yarn.lock` in a different way. Pinning should be implemented alongside lockfiles, not as an add-on to them, since it's conceptually a separate feature entirely. See https://github.com/raxod502/straight.el/issues/246#issuecomment-650188900 for notes on the implementation.

What is abundantly clear is that this entire situation is needlessly confusing, because there are several different things that behave similarly but yet should not be confused. That is a clear area for improvement.

> straight is still able to load the package

That's because it can find the recipe in the current checked-out revision of the recipe repository. It's not like it silently checks out the revision listed in your lockfile and then deletes that checkout; that would be far too slow. `straight.el` defers always to whatever you put in your local repositories manually, and only offers reproducibility as an optional thing that you can request on demand (`straight-thaw-versions`, `straight-normalize-all`).

Although `straight.el` uses extensive caching, you would not notice any behavior difference if all of it were removed. It is strictly for performance enhancement and should not affect user-visible behavior at any time.

**Comment by ThibautVerron** [comment] 2020-07-18 14:01
> The reason I selected the term lockfile is that other package managers such as Yarn, RubyGems, Poetry, etc. use the word in the same way as straight.el.

That's a good enough reason. As you can probably tell by now I'm not familiar with any of those, but it makes sense now.

> Well, you can hardly say straight.el is not helping, no? Doing it without straight.el would require you to manually add to the load path, generate autoloads, byte-compile, and remember to do that all again every time you make a change. 

To be honest I don't remember how I was doing it before straight. I guess use-package was taking care of the autoloads, and that package.el was somehow helping me too, but it could very well be that I was sometimes loading non-compiled elisp files.

> You can specify (straight-use-package '(el-patch :fork (:repo "my-name/el-patch"))) and straight.el will do this automatically (plus validate that they stay correct, offer to push changes to your fork, etc.), although the UX could be improved.

Ooh, very good to know, thanks! 

That also opens a lot of possibilities for a smart way of handling dirty local copies, if that information (whether the recipe is a fork or not) is available to straight.

As for the UX, short of allowing straight to edit the users init files (and I'm very much not in favor of that) I don't see what could be done. Maybe a separate file, ala custom.el... but it would immediately be messy.

> Also you'd be in hot water if working with a package that uses a nontrivial :files directive in its MELPA recipe.

That never happened, but how would it be a problem? The directive can restrict the available files, but it should never hurt to have more?

> Pinning should be implemented alongside lockfiles, not as an add-on to them, since it's conceptually a separate feature entirely. See #246 (comment) for notes on the implementation.

I agree, and thanks for the reference. 

> straight.el defers always to whatever you put in your local repositories manually, and only offers reproducibility as an optional thing that you can request on demand (straight-thaw-versions, straight-normalize-all).

Right, once the previous confusion is cleared it makes more sense. :)

**Comment by raxod502** [comment] 2020-07-19 13:03
> I guess use-package was taking care of the autoloads

`use-package` allows you to create autoloads manually, for example it autoloads any commands you mention in a `:bind` specification. But it completely ignores the autoloads of the package itself, hence "`use-package` is not a package manager (despite the name)".

> it could very well be that I was sometimes loading non-compiled elisp files

You most likely were if you edited source code of packages, since `package.el` has no facility whatsoever for rebuilding a package, even manually. You have to invoke the byte-compiler and autoload generator yourself.

> a smart way of handling dirty local copies, if that information (whether the recipe is a fork or not) is available to straight

This information is indeed available. That's an interesting idea which could be a good compromise between automation and safety. After all it seems unlikely that many people will be interested in keeping around changes that are purely local and don't have a fork on which to be published (or at least such a use case would be mostly mutually exclusive with wanting to have a reproducible configuration).

> short of allowing straight to edit the users init files (and I'm very much not in favor of that) I don't see what could be done

I don't mean introducing a new system, I just mean improving the existing one. For example, it could be possible for `straight.el` to detect that you had just changed the recipe, and automatically offer to normalize the repository (== add your fork as a remote and fetch) at that point (rather than your needing to manually `M-x straight-normalize-package`).

> The directive can restrict the available files, but it should never hurt to have more?

Ideally, but `:files` directives sometimes rearrange the directory structure and packages sometimes (unfortunately) rely on this in surprising ways. I will admit it's not common, though.

Another issue is that many packages don't have `*.elc` in their `.gitignore` files, because nobody builds the package from source. These and other issues are why `straight.el` has an explicit build/repo separation.

**Comment by ThibautVerron** [comment] 2020-07-20 08:36
> use-package allows you to create autoloads manually, for example it autoloads any commands you mention in a :bind specification. But it completely ignores the autoloads of the package itself, hence "use-package is not a package manager (despite the name)"

Yes, but package.el does, no? I don't really know, I've never run into any problem with that.

> I don't mean introducing a new system, I just mean improving the existing one. For example, it could be possible for straight.el to detect that you had just changed the recipe, and automatically offer to normalize the repository (== add your fork as a remote and fetch) at that point (rather than your needing to manually M-x straight-normalize-package).

Oh you mean that the user still adds the fork manually to his init.el, but straight ensures that the local package is consistent with the recipe when evaluating straight-use-package? Yes it makes sense.

> Ideally, but :files directives sometimes rearrange the directory structure and packages sometimes (unfortunately) rely on this in surprising ways. I will admit it's not common, though.

I would expect and hope that those packages also have a way of ensuring directory structure without melpa.

> Another issue is that many packages don't have *.elc in their .gitignore files, because nobody builds the package from source. 

I don't get it. How else do you develop a package? 

Even now that I am using straight, for packages I do real work on (as opposed to fork-patch-PR), I still build from source (using cask), for example to run unit tests in a separate emacs instance.

**Comment by raxod502** [comment] 2020-07-20 12:56
> package.el does, no?

Yes, fair enough, although it won't re-generate them if the package is changed.

> you mean that the user still adds the fork manually to his init.el, but straight ensures that the local package is consistent with the recipe when evaluating straight-use-package?

Indeed.

> I would expect and hope

Same here, but I've been taught by experience to prepare for disappointment when looking at existing software packaging... :'(

> I don't get it. How else do you develop a package?

I have asked myself this question as well. My understanding is, with extreme awkwardness. In this case one solution is to just not bother byte-compiling. At least I could not figure out how have a proper development workflow without everything being a complete mess, and other users of `straight.el` have told me the same thing. Frankly it shocked me that `straight.el` didn't _already_ exist.

> I still build from source (using cask), for example to run unit tests in a separate emacs instance.

Why do it separately? You can still run Cask from the `straight.el` repository directory.

**Comment by ThibautVerron** [comment] 2020-08-03 07:59
Sorry for the delay.

> Yes, fair enough, although it won't re-generate them if the package is changed.

It will regenerate them if you update the package using package.el?

> Why do it separately? You can still run Cask from the straight.el repository directory.

A bunch of reasons, mostly FUD. Essentially, this setup works, and I don't feel confident working in directories which are managed by software I don't control. Cloud synchronizers are bad enough... Now that I have more experience with the straight source code it would be different, but still, why change what isn't broken?

Also, occasionally my packages get broken and when it happens I find it convenient to have two versions cohabitate: the one in straight/repos/, pulled from the master branch, with only the code, via melpa, and the one in devel/ with all the support files, in whichever broken and unpushed state it may be.

**Comment by raxod502** [comment] 2020-08-09 14:28
> It will regenerate them if you update the package using package.el?

Yes, but not if you edit them manually or via Git, both of which I personally do all the time.

> A bunch of reasons, mostly FUD.

Fair enough. But for what it's worth, `straight.el` intends to explicitly support all of the things you want to do, and if it does not then it is a bug.

**Comment by ThibautVerron** [comment] 2020-08-10 12:59
> Yes, but not if you edit them manually or via Git, both of which I personally do all the time.

Right. I guess I was always manually calling `require` for those packages I would develop myself, or possibly even `byte-compile-file t`. 

I understand that this whole conversation has gone quite circular. I didn't investigate what straight could do to avoid some hassles because I didn't feel the need to do so because I already worked around said hassles.

> 
> > A bunch of reasons, mostly FUD.
> 
> Fair enough. But for what it's worth, `straight.el` intends to explicitly support all of the things you want to do, and if it does not then it is a bug.

I have no doubt that I will be using more and more of those features as time passes, but I won't jump all in.

Thanks a lot for all the information, as far as I'm concerned the issue is resolved and can be closed.

**Closed** 2020-08-14 15:48 UTC
Labels: discussion, lockfiles, recipe repositories, ux, waiting on response
