### ISSUE TITLE
Symbol's function is void: comp-deferred-compilation-deny-list

### ISSUE THREAD

**Issue by Ultra-Hax** [raxod502/straight.el#764] opened 2021-05-19 15:37 UTC
This started happening after updating Emacs. I am on pgtk-nativecomp

**Comment by Ultra-Hax** [comment] 2021-05-19 15:40
I found a workaround `(defvar comp-deferred-compilation-deny-list ())` I just add this before bootstrap however I would like this to stay open until I don't need this.

**Comment by progfolio** [comment] 2021-05-19 15:41
What is the output of `M-x straight-version`?

**Comment by progfolio** [comment] 2021-05-19 15:42
Duplicate of #757

**Closed** 2021-05-19 15:44 UTC

**Comment by progfolio** [comment] 2021-05-19 17:58
I've merged the develop branch into the master branch, so both versions should work appropriately now.
