### ISSUE TITLE
Using bootstrap in README is causing symbol void error

### ISSUE THREAD

**Issue by notmgsk** [raxod502/straight.el#196] opened 2017-12-09 17:30 UTC
Using the bootstrap code that is currently in the README (displayed on the package's homepage) results in an error. To be clear, the code is 

    (let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
          (bootstrap-version 2))
      (unless (file-exists-p bootstrap-file)
        (with-current-buffer
            (url-retrieve-synchronously
             "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage))

which results in the following error:

> Bootstrapping straight.el...
> if: straight.el bootstrap failed: Symbol’s value as variable is void: straight-repository-branch

Using `straight.el/master/install.el` works, however:

    (let ((bootstrap-file (concat user-emacs-directory "straight/bootstrap.el"))
          (bootstrap-version 2))
      (unless (file-exists-p bootstrap-file)
        (with-current-buffer
            (url-retrieve-synchronously
             "https://raw.githubusercontent.com/raxod502/straight.el/master/install.el"
             'silent 'inhibit-cookies)
          (goto-char (point-max))
          (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage))

> t

**Comment by raxod502** [comment] 2017-12-09 21:24
This was very much a dumb mistake on my part, sorry. The problem should be fixed now with no changes necessary on your end; please let me know if it is not.

**Closed by raxod502** 2017-12-09 21:24 UTC

**Comment by notmgsk** [comment] 2017-12-09 21:42
Lovely. Fixed on my end.

**Comment by shackra** [comment] 2019-08-25 05:21
got hit by this bug **in 2019**!

**Comment by raxod502** [comment] 2019-08-25 16:53
@shackra Can't reproduce. Can you open a new issue with the full contents of your init-file, your operating system, and Emacs version?

**Comment by shackra** [comment] 2019-08-25 23:37
It was fixed by changing the branch `develop` to `master`

no rush, dear Sir
