### ISSUE TITLE
straight-freeze-versions + straight-thaw-versions is not no-op

### ISSUE THREAD

**Issue by antifuchs** [raxod502/straight.el#294] opened 2018-07-14 00:38 UTC
As suggested in https://github.com/raxod502/straight.el/issues/292#issuecomment-404868441, I made a reproducer repo for the issue I'm seeing: https://github.com/antifuchs/straight.el-repro-case-1 - it's an init file pulling in ace-window, and a lock file locking that to an older version.

To reproduce:

1. Clone the repo above
2. `emacs -Q init.el`
3. `C-M-x` to evaluate the init file (this will bootstrap straight, so it's going to take a while)
4. `M-x straight-thaw-versions`
5. `M-x straight-freeze-versions`
6. In the clone from above, run `git diff`

On my machine, `git diff` says that the `ace-window` version changed to the latest. I'd expect there to be no differences. This also reproduces for me if I restart emacs between steps 4 and 5.

I'm testing this on `GNU Emacs 26.1 (build 1, x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2018-04-15` - the latest bottle from https://github.com/railwaycat/homebrew-emacsmacport

**Comment by antifuchs** [comment] 2018-07-14 10:06
I just stepped through the freeze process, and it looks like `straight-vc-git--ensure-head-pushed` (via `straight-vc-push-to-remove`, invoked from the freeze function) is what resets the checkout for `ace-window` to the `master` branch. I'll step through this some more & hopefully will find the exact trace of git things that happen when it does.

**Comment by raxod502** [comment] 2018-07-14 15:33
Oh. Yes, that is the intended behavior, except that it causes this horrible effect because #66 has not been fixed yet. I think that #66 is the correct way to address this problem—you do want to make sure that the default branch is checked out (otherwise how can you be sure that the commit will be accessible when the configuration is cloned on another machine?) but _of course_ `M-x straight-thaw-versions` followed by `M-x straight-freeze-versions` should be a no-op, whereas currently it is not. Thawing versions should reset the default branch rather than detaching HEAD.

**Comment by antifuchs** [comment] 2018-07-15 13:39
Ah, that makes a ton of sense - I think resetting the branch to the previously checked-out rev would be quite reasonable (if that rev was an ancestor of the remote's pushed branch).

**Comment by raxod502** [comment] 2019-05-04 14:42
This should be fixed by https://github.com/raxod502/straight.el/pull/375.

**Closed by raxod502** 2019-05-04 14:42 UTC
Labels: bug, critical, lockfiles
