### ISSUE TITLE
Org-mode Switching to new Git repositories

### ISSUE THREAD

**Issue by UminoMashiro** [raxod502/straight.el#847] opened 2021-09-23 03:23 UTC
https://list.orgmode.org/8735pz50bw.fsf@gnu.org/

https://git.savannah.gnu.org/git/emacs/org-mode.git

**Comment by UminoMashiro** [comment] 2021-09-23 04:37
```
error: :pre-build command error in "org" recipe (error "Failed to run \"git\"; see buffer *straight-process*")
```
```
$ cd .config/emacs/straight/repos/org/lisp/
$ git describe --match release\* --abbrev\=0 HEAD

fatal: No names found, cannot describe anything.

[Return code: 128]
```

**Comment by progfolio** [comment] 2021-09-23 04:49
We've got to tweak how we're building org-version.el because there are no tags in the elpa repo. Working on it now.

**Comment by UminoMashiro** [comment] 2021-09-23 04:51
Thanks!

**Comment by progfolio** [comment] 2021-09-23 04:52
Should be good now. Confirmed with the following test case:


<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "org-elpa.straight"
  :pre-bootstrap 
  (setq straight-repository-user "progfolio" straight-repository-branch "fix/org-repo-address")
  :post-bootstrap 
  (straight-use-package 'org)
  (org-version nil 'full 'message))
```
</details>

- Test run at: `2021-09-23 00:50:30`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> fix/org-repo-address, fork/fix/org-repo-address) 57a757b 2021-09-23`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-09-16`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> fix/org-repo-address, origin/fix/org-repo-address) 57a757b 2021-09-23
Cloning org...
Cloning org...done
Building org...
Building org...done

Org mode version 9.5-dev (9.5-dev-gc9dc66 @ /tmp/org-elpa.straight/straight/build/org/)
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 6860800b 2021-09-19
"gnu-elpa-mirror"         n/a                  master a4cb567 2021-08-29
"el-get"                  melpa                master b5a5a405 2021-09-01
"emacsmirror-mirror"      n/a                  master fc970dc 2021-08-27
"straight"                n/a                  fix/org-repo-address 57a757b 2021-09-23
"org"                     org-elpa             main c9dc6603a 2021-09-21


```
</details>

**Comment by progfolio** [comment] 2021-09-23 04:54
Merged into "develop" branch. Testing appreciated.

**Comment by djgoku** [comment] 2021-09-23 19:33
I am getting `version-to-list: Invalid version syntax: ‘9.5-dev’` with `prerelease (HEAD -> develop, origin/develop) 0b0dcf8 2021-09-23`.

I tried deleting straight.el repos/build directory and re-building but that didn't help and I still get the error.

**Comment by progfolio** [comment] 2021-09-23 20:10
@djgoku: Please evaluate the following in your \*scratch* buffer. It will install straight.el and org.el in a clean environment using a subprocess. Once the test has finished, a buffer (\*straight-bug-report-process*) will pop up with the results. Copy the results here.

<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "org-elpa.straight"
  :pre-bootstrap 
  (setq straight-repository-branch "develop")
  :post-bootstrap 
  (straight-use-package 'org)
  (org-version nil 'full 'message))
```
</details>

- Test run at: `2021-09-23 16:08:01`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 0b0dcf8 2021-09-23`
- emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-09-16`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 0b0dcf8 2021-09-23
Cloning org...
Cloning org...done
Building org...
Building org...done

Org mode version 9.5-dev (9.5-dev-gc9dc66 @ /tmp/org-elpa.straight/straight/build/org/)
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 6860800b 2021-09-19
"gnu-elpa-mirror"         n/a                  master a4cb567 2021-08-29
"el-get"                  melpa                master b5a5a405 2021-09-01
"emacsmirror-mirror"      n/a                  master fc970dc 2021-08-27
"straight"                n/a                  develop 0b0dcf8 2021-09-23
"org"                     org-elpa             main c9dc6603a 2021-09-21


```
</details>

**Comment by djgoku** [comment] 2021-09-23 20:14
<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "org-elpa.straight"
  :pre-bootstrap 
  (setq straight-repository-branch "develop")
  :post-bootstrap 
  (straight-use-package 'org)
  (org-version nil 'full 'message))
```
</details>

- Test run at: `2021-09-23 15:13:07`
- system-type: `darwin`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 0b0dcf8 2021-09-23`
- emacs-version: `GNU Emacs 28.0.50 (build 2, x86_64-apple-darwin20.4.0, NS appkit-2022.44 Version 11.3.1 (Build 20E241))
 of 2021-06-03`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 0b0dcf8 2021-09-23
Cloning org...
Cloning org...done
Building org...
Building org...done

Org mode version 9.5-dev (9.5-dev-gc9dc66 @ /var/folders/lw/t4g3mxhj0115lll5zk99csm80000gn/T/org-elpa.straight/straight/build/org/)
Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 6860800b 2021-09-19
"gnu-elpa-mirror"         n/a                  master a4cb567 2021-08-29
"el-get"                  melpa                master b5a5a405 2021-09-01
"emacsmirror-mirror"      n/a                  master fc970dc 2021-08-27
"straight"                n/a                  develop 0b0dcf8 2021-09-23
"org"                     org-elpa             main c9dc6603a 2021-09-21


```
</details>

**Comment by progfolio** [comment] 2021-09-23 20:17
That suggests that it built cleanly in the test environment.
Try removing org's repo dir (e.g. ~/.emacs.d/straight/repos/org), build dir, and the build-cache file (should be at ~/.emacs.d/straight/build-cache.el), then restarting emacs from the command line with --debug-init.
If it throws an error, copy the backtrace here.

**Comment by progfolio** [comment] 2021-09-23 20:26
I'm able to reproduce. Working on a solution.

**Comment by progfolio** [comment] 2021-09-23 21:41
@djgoku: Should be fixed on the "develop" branch. Testing appreciated. If you're interested in the details, see #849.

**Closed** 2021-09-23 21:43 UTC

**Comment by djgoku** [comment] 2021-09-23 21:55
> @djgoku: Should be fixed on the "develop" branch. Testing appreciated. If you're interested in the details, see #849.

Deleted straight.el and org build/repos and restarted emacs and all is working now. Thanks!

**Comment by dixius99** [comment] 2021-09-26 15:00
I'm sorry if this is a dense question, but when I ran `straight-pull-all` this morning, I think I ran in to the problem described above, but I don't know how to fix it. Here's what I see in `straight-process`:

```
Cloning into '/Users/michael/.config/emacs/straight/repos/org'...
fatal: unable to update url base from redirection:
  asked for: https://code.orgmode.org/bzg/org-mode.git/info/refs?service=git-upload-pack
   redirect: https://git.savannah.gnu.org/cgit/emacs/org-mode.git/?service=git-upload-pack

[Return code: 128]

$ cd /Users/michael/.config/emacs/straight/repos/org/
$ git branch -r

[File error while Setting current directory]
```

**Comment by progfolio** [comment] 2021-09-26 15:40
Are you using a proxy or any git URL rewrite rules?

**Comment by dixius99** [comment] 2021-09-26 15:58
> Are you using a proxy or any git URL rewrite rules?

I'm not, but I think I figured out what I was doing wrong. I added to my config `(setq straight-repository-branch "develop")`, deleted my `straight` folder, and now it appears to be working.

Sorry for the false alarm.

**Comment by progfolio** [comment] 2021-09-26 16:03
Ah, yes. Sorry. The change hasn't been merged into the master branch yet.
