### ISSUE TITLE
Use `straight.el` to manage local customized configuration scripts or small functions stored in a directory layout with hierarchies.

### ISSUE THREAD

**Issue by hongyi-zhao** [raxod502/straight.el#934] opened 2022-03-21 01:07 UTC
Today, I noticed a nice small elisp script [character-aliases.el](https://lists.gnu.org/archive/html/help-gnu-emacs/2022-03/bin3cfCvSPcl8.bin), which can Find all the name and alias corresponding to a codepoint in Emacs. I want to use `straight.el` to manage such scripts for convenience. For example, I stored this script in the following directory:

```bash
custom-repos/character-aliases/character-aliases.el 
```

I want to let `straight.el` manage the `custom-repos` for me, alongside with its default `~/.emacs.d/straight/repos`. Do you have any tips for the configuration to achieve the above purpose?

Regards,
HZ

**Comment by progfolio** [comment] 2022-03-24 21:01
See the comment here:

https://github.com/raxod502/straight.el/issues/807#issuecomment-886115501

**Comment by hongyi-zhao** [comment] 2022-03-25 13:48
I put the script under the directory `~/.emacs.d/straight/repos/hongyi-zhao-custom/`, and use the following configuration in my `~/.emacs.d/init.el`:

```emacs-lisp
(straight-use-package
 '("hongyi-zhao-custom" :type nil :local-repo "hongyi-zhao-custom"))
```
When Emacs starts, the following error is triggered:

![image](https://user-images.githubusercontent.com/11155854/160132212-946058f6-b4bf-4718-856c-3d15a02b3d36.png)

**Comment by progfolio** [comment] 2022-03-25 22:02
The error message:

```
Wrong type argument: symbolp, hongyi-zhao-custom
```

Illustrates the problem.
Note the first example here:

https://github.com/raxod502/straight.el/tree/develop#the-recipe-format

The first element of your recipe should be a symbol, not a string.

**Comment by hongyi-zhao** [comment] 2022-03-26 01:36
Now, I changed to the following configuration:

```emacs-lisp
(straight-use-package
 '(hongyi-zhao-custom :type nil :local-repo "hongyi-zhao-custom"))
```

This fixed the above problem, and I noticed that the following build directory has been created:
```bash
$ ls ~/.emacs.d/straight/build/hongyi-zhao-custom/
character-aliases.el  character-aliases.elc  hongyi-zhao-custom-autoloads.el
```
But the function/command defined in the `character-aliases.el`, i.e.,  `wd-char-aliases-show` still can't be loaded automatically:

![image](https://user-images.githubusercontent.com/11155854/160219531-d4cdcec5-236b-4246-9d11-b4eff88b80ad.png)

For the complete content of `character-aliases.el`, please refer to the following:

```emacs-lisp
(defun wd-char-aliases-query (char)
  (let* ((wikidata-endpoint "https://query.wikidata.org/sparql")
	 (url-request-method "POST")
	 (url-request-extra-headers
  	  '(("Accept" . "application/sparql-results+json")
  	    ("Content-Type" . "application/x-www-form-urlencoded")))
	 (sparql-query-template
	  "select distinct (lcase(?label) as ?label)
	   where
	   {
	     ?char wdt:P31/wdt:P279* wd:Q3241972;
		   wdt:P487 \"%s\".
	     { ?char skos:altLabel ?label }
	     union
	     { ?char rdfs:label ?label }
	     filter ( LANG(?label) = \"en\" )
	     filter ( fn:not(fn:matches(?label, \"U\\\\+([a-fA-F]|[0-9])+\")) )
	     filter ( STRLEN(?label) > 2 )
	   }"
	  )
	 (sparql-query (format sparql-query-template
  			       (string char)))
	 (url-request-data
  	  (concat "query=" (url-hexify-string sparql-query))))
    (let  ((buf (url-retrieve-synchronously wikidata-endpoint)))
      (with-current-buffer buf
	(goto-char (point-min))
	(re-search-forward "^$")
	(forward-line)
	(buffer-substring (point) (point-max))))))

(defun wd-char-aliases (char)
  (let* ((query-result (wd-char-aliases-query char))
	 (json (json-read-from-string query-result))
	 (results (cdr (assq 'results json)))
	 (bindings (cdr (assq 'bindings results))))
    (mapcar (lambda (b)
  	      (let ((l (assq 'label b)))
  		(cdr (assq 'value l))))
  	    bindings)))

(defun wd-char-aliases-show ()
  (interactive)
  (let* ((aliases (wd-char-aliases (char-after))))
    (if (null aliases)
	(message "No character aliases found")
      (with-output-to-temp-buffer "*Character Aliases*"
	(dolist (a aliases)
	  (princ a)
	  (terpri))))))
```

**Comment by progfolio** [comment] 2022-03-26 17:54
I see no autoload cookies for those definitions, so I would not expect them to be autoloaded. See relevant Emacs documentation:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html

**Comment by hongyi-zhao** [comment] 2022-03-27 01:52
Can `straight.el` add these autoload cookies automatically?

**Comment by progfolio** [comment] 2022-03-28 23:18
The elisp file you've linked to is not a proper package. It does not provide a named feature, so loading will fail even if a function is autoloaded and it's directory is in the load-path. I would suggest searching for tutorials along the lines of "Elisp packaging tutorial", which turns up the following (among others):

https://www.emacswiki.org/emacs/MakingPackages

You can use the built in flymake-mode (which integrates with the built in checkdoc program) to correct any errors with your package.

I'm going to close this, as the issue is not specific to straight, but more of a general elisp question.
I hope the info is useful. good luck!

**Closed by progfolio** 2022-03-28 23:18 UTC
Labels: support

**Comment by hongyi-zhao** [comment] 2022-03-29 00:49
> You can use the built in flymake-mode (which integrates with the built in checkdoc program) to correct any errors with your package.

According to the description [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Flymake.html):

> Flymake mode is a minor mode that performs on-the-fly syntax checking for many programming and markup languages, including C, C++, Perl, HTML, and TeX/LaTeX.

If I have a problem in the development logic of the package, such as the problem we discussed here.This tool seems unlikely to give suggestions.

BTW, I'm using [flycheck](https://www.flycheck.org/en/latest/) for this type of work.

**Comment by hongyi-zhao** [comment] 2022-03-29 07:18
> I see no autoload cookies for those definitions, so I would not expect them to be autoloaded. See relevant Emacs documentation:
> 
> https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html

The following revision fixes the problem discussed here:

```emacs-lisp
(defun wd-char-aliases-query (char)
  (let* ((wikidata-endpoint "https://query.wikidata.org/sparql")
	 (url-request-method "POST")
	 (url-request-extra-headers
  	  '(("Accept" . "application/sparql-results+json")
  	    ("Content-Type" . "application/x-www-form-urlencoded")))
	 (sparql-query-template
	  "select distinct (lcase(?label) as ?label)
	   where
	   {
	     ?char wdt:P31/wdt:P279* wd:Q3241972;
		   wdt:P487 \"%s\".
	     { ?char skos:altLabel ?label }
	     union
	     { ?char rdfs:label ?label }
	     filter ( LANG(?label) = \"en\" )
	     filter ( fn:not(fn:matches(?label, \"U\\\\+([a-fA-F]|[0-9])+\")) )
	     filter ( STRLEN(?label) > 2 )
	   }"
	  )
	 (sparql-query (format sparql-query-template
  			       (string char)))
	 (url-request-data
  	  (concat "query=" (url-hexify-string sparql-query))))
    (let  ((buf (url-retrieve-synchronously wikidata-endpoint)))
      (with-current-buffer buf
	(goto-char (point-min))
	(re-search-forward "^$")
	(forward-line)
	(buffer-substring (point) (point-max))))))

(defun wd-char-aliases (char)
  (let* ((query-result (wd-char-aliases-query char))
	 (json (json-read-from-string query-result))
	 (results (cdr (assq 'results json)))
	 (bindings (cdr (assq 'bindings results))))
    (mapcar (lambda (b)
  	      (let ((l (assq 'label b)))
  		(cdr (assq 'value l))))
  	    bindings)))

;;;###autoload
(defun wd-char-aliases-show ()
  (interactive)
  (let* ((aliases (wd-char-aliases (char-after))))
    (if (null aliases)
	(message "No character aliases found")
      (with-output-to-temp-buffer "*Character Aliases*"
	(dolist (a aliases)
	  (princ a)
	  (terpri))))))
```

The Emacs configuration:

```emacs-lisp
(use-package wd-char-aliases-show
  :straight (:type nil :local-repo "hongyi-zhao-custom/character-aliases")
  )
```

Currently, the file directory hierarchy used is as follows:

```
werner@X10DAi-00:~/.emacs.d/straight/repos$ tree -F hongyi-zhao-custom/
hongyi-zhao-custom/
└── character-aliases/
    └── character-aliases.el

1 directory, 1 file
```
