### ISSUE TITLE
Rebuild happens when opens a different version emacs

### ISSUE THREAD

**Issue by feng-qi** [raxod502/straight.el#893] opened 2021-12-02 09:15 UTC
I recently want to try emacs with tree-sitter support. When I run the newly built emacs, the rebuild starts. This rebuild also happens when some time ago I want to see if a feature is supported by a older version emacs.

And it will rebuild again when I switch back to the emacs version I normally use.

This is very time consuming. I don't know if there's already a method to handle this situation in straight. If not, can we add some facilities to handle this better by, for example, multiple build directories?

Thanks.

**Comment by progfolio** [comment] 2021-12-02 18:12
Duplicate of https://github.com/raxod502/straight.el/issues/484

Please see discussion there.

**Closed by progfolio** 2021-12-02 18:12 UTC
Labels: support

**Comment by feng-qi** [comment] 2021-12-03 10:48
Thanks. This comment https://github.com/raxod502/straight.el/issues/484#issuecomment-927365350 does help me a lot. The following simple setting seems to meet all my needs.

```elisp
(setq straight-build-dir (concat "build-" emacs-version))
```
