### ISSUE TITLE
org-capture error "Capture template ‘t’: Symbol’s value as variable is void: org-fold-core-style")

### ISSUE THREAD

**Issue by penguinsam** [raxod502/straight.el#947] opened 2022-05-13 07:27 UTC
After doing upgrade to Emacs 28.1 and fresh pull using straight, org-capture end up stop working with the error like this:
```
Debugger entered--Lisp error: (error "Capture template ‘t’: Symbol’s value as variable is void: org-fold-core-style")
  signal(error ("Capture template ‘t’: Symbol’s value as variable is void: org-fold-core-style"))
  error("Capture template `%s': %s" "t" "Symbol’s value as variable is void: org-fold-core-style")
  org-capture(nil)
  funcall-interactively(org-capture nil)
  call-interactively(org-capture record nil)
  command-execute(org-capture record)
  execute-extended-command(nil "org-capture" "org-cap")
  funcall-interactively(execute-extended-command nil "org-capture" "org-cap")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I had been working since v27 on Mac, and ok with 28.1 in Windows...

system-type: `Mac OS 12.3.1`
straight-version: `prerelease (HEAD -> master, origin/master, origin/HEAD) af5437f 2021-09-27`
emacs-version: `GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.4.0, Carbon Version 165 AppKit 2113.4) of 2022-05-04`
org-version: `Org mode version 9.5.2 (release_9.5.2-25-gaf6f12 @ /Users/sam/.emacs.d/straight/build/org/)`

**Comment by progfolio** [comment] 2022-05-13 17:28
Closing for now as this sounds more like an upstream bug in Org mode than a bug in straight.el. There has been recent work on Org which adds a different folding backend, org-fold-core, which is still being worked on. Please report this bug upstream at this address:

emacs-orgmode@gnu.org

If you can determine that the issue is with straight.el just comment here and we can re-open the issue. Thank you.

**Closed by progfolio** 2022-05-13 17:28 UTC
Labels: support

**Comment by progfolio** [comment] 2022-05-13 17:34
@yantar92 should have some insight on this, but it's best to report it upstream.

**Comment by yantar92** [comment] 2022-05-14 00:56
> @yantar92 should have some insight on this, but it's best to report it upstream.

I am not sure if it is upstream bug. Sounds like mixed install when part
of built-in Org mode version is loaded first and the other part is
loaded by straight.

`org-fold-core-style` cannot be void unless it is not loaded.

**Comment by penguinsam** [comment] 2022-05-14 02:53
> @yantar92 should have some insight on this, but it's best to report it upstream.
> I am not sure if it is upstream bug. Sounds like mixed install when part of built-in Org mode version is loaded first and the other part is loaded by straight. `org-fold-core-style` cannot be void unless it is not loaded.

I second that. Last night I tried to load my old init (which not using straight and load the built in org 9.5.2), the warning gone. I then copy the built in org folder to straight/build and load straight, the warning gone also.

**Comment by progfolio** [comment] 2022-05-14 19:25
I'm unable to reproduce the behavior you're describing via the following test case:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'org)
  (require 'org-capture)
  (setq org-capture-templates
        '(("t" "test" plain
           (file "/tmp/test.org")
           "PASS" :immediate-finish t)))
  (org-capture nil "t")
  (with-current-buffer
      (find-file-noselect "/tmp/test.org")
    (message "%S"
             (buffer-string))))
```
</details>

- Test run at: `2022-05-14 15:22:07`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 4517e11 2022-04-13`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6)
 of 2022-05-13`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 99ba608 2022-05-13
Cloning org...
Cloning org...done
Building org...
Building org...done

Warning (comp): ox-texinfo.el: Warning: the function ‘org-back-to-heading’ might not be defined at runtime.
Warning (comp): ox-texinfo.el: Warning: the function ‘org-next-visible-heading’ might not be defined at runtime.
Warning (comp): ox-texinfo.el: Warning: the function ‘org-at-heading-p’ might not be defined at runtime.
Warning (comp): ox-org.el: Warning: the function ‘org-back-to-heading’ might not be defined at runtime.
Warning (comp): ox-org.el: Warning: the function ‘org-next-visible-heading’ might not be defined at runtime.
Warning (comp): ox-org.el: Warning: the function ‘org-at-heading-p’ might not be defined at runtime.
"PASS
"
Packages:
"straight"                n/a                  develop 99ba608 2022-05-13
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master ebc43ea6 2022-05-14
"gnu-elpa-mirror"         n/a                  master a388b8a 2022-05-12
"el-get"                  melpa                master 93533097 2021-12-24
"emacsmirror-mirror"      n/a                  master e2d1379 2022-05-13
"org"                     org-elpa             main 513ab7c48 2022-05-14


```
</details>

You can try and evaluate it on your end in your scratch buffer and share the results here.

> I then copy the built in org folder to straight/build and load straight,

I would recommend against that. Have you tried just deleting  straight/builds/org and straight/repos/org-mode to see if a fresh clone solves the issue?

**Comment by yantar92** [comment] 2022-05-15 02:02
Nicholas Vollmer ***@***.***> writes:

> I'm unable to reproduce the behavior you're describing via the following test case:
>
> ```emacs-lisp
> (straight-bug-report
>   :post-bootstrap 
>   (straight-use-package 'org)
>   (require 'org-capture)

AFAIK, this and similar problem are caused by something like following:

(require 'org) ; this _partially_ loads built-in version of Org
;; You can remove the above require to make the error go away
(straight-use-package 'org)
(require 'org)
(message "%S" org-fold-core-style)

With (require 'org) usually hidden behind
(straight-use-package 'some-other-package-loading-org)

Best,
Ihor

**Comment by velppa** [comment] 2022-05-29 13:23
I had the same issue, straight clones the latest master branch of Org Mode if there are dependencies that it manages. So there was Org 9.5.3 and Org 9.6 installed at the same time.

Solved by explicitly saying to use built-in Org Mode:

```
(straight-use-package '(org :type built-in))
```

**Comment by yantar92** [comment] 2022-05-29 13:29
> I had the same issue, straight clones the latest master branch of Org Mode if there are dependencies that it manages. So there was Org 9.5.3 and Org 9.6 installed at the same time.

Note that the same problem may happen with packages other than Org. For
example, I have dash.el installed using Linux package manager. However,
I need a newer version of dash.el for some packages.

I had to be careful about not loading anything that depends on dash.el
before my (straight-use-package 'dash) statement.

**Comment by penguinsam** [comment] 2022-05-30 00:41
> I had the same issue, straight clones the latest master branch of Org Mode if there are dependencies that it manages. So there was Org 9.5.3 and Org 9.6 installed at the same time.
> 
> Solved by explicitly saying to use built-in Org Mode:
> 
> ```
> (straight-use-package '(org :type built-in))
> ```

I attempted to solve in this way but not working. That's why I had to copy the build in directory to straight.

**Comment by penguinsam** [comment] 2022-05-30 00:42
> 

Yes I did before but not work as well :(
