### ISSUE TITLE
Org mode old version

### ISSUE THREAD

**Issue by nanounanue** [raxod502/straight.el#411] opened 2019-09-08 02:10 UTC
I tried the solution in #371  and it worked, but my org version is still `9.1`:

```
GNU Emacs 27.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-08-10 [2 times]

Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /home/nanounanue/.emacs.d/straight/build/org/)
```

If I execute `straight-rebuild-package` for `org` I get:

```
Org mode version 9.2.6 (release_9.2.6-521-gf2f646 @ /home/nanounanue/.emacs.d/straight/build/org/)
```
But if I restart emacs, I go back to the version `9.1.9`

**Comment by raxod502** [comment] 2019-09-08 16:48
What if you exit Emacs, delete `~/.emacs.d/straight/build/org`, and then restart? Maybe the bad `.elc` is getting loaded and affecting byte-compilation in the future.

**Comment by nanounanue** [comment] 2019-09-11 17:12
That worked! Thank you so much.

**Comment by dangom** [comment] 2019-09-12 01:43
Same issue here

**Comment by Wetlize** [comment] 2019-09-13 15:52
Same issue here. It looks like `straight.el`'s hack is being broken?

You might will be able to reproduce the issue with the next recipe:
``` emacs-lisp
;;;  init.el -*- lexical-binding: t; -*-

(require 'cl-lib)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; NOTE: Enabling/disabling this, before running Emacs or downloading
;; org-plus-contrib doesn't change anything (visibly).
(setq-default straight-fix-org nil)

;; Removes in-build version from the `load-path'
;; (when-let (orglib (locate-library "org" nil load-path))
;;   (setq-default load-path (delete (substring (file-name-directory orglib) 0 -1)
;;                                   load-path)))

(cl-assert (memq 'org-elpa straight-recipe-repositories))
(straight-use-package 'org-plus-contrib)

;; NOTE:
;;
;; If you run `org-version' right after downloading (without restarting Emacs)
;; the latest version - it will message 9.2.6 org's version.
;;
;; If you restart Emacs with enabled `load-path' clean-up thingy (line
;; 23) you will get "File is missing: Cannot open load file, No such file or
;; directory, org-version.el", even though "..straight/build/org-plus-contrib"
;; being at the head of the `load-path'.
;;
;; If you comment out the `load-path' clean-up thingy it will load the in-build
;; org-mode version (`org-version' prints 9.1.9).
;; The load path will place "/usr/share/emacs/26.1/lisp/org" close to the tail
;; and "../usr/share/emacs/26.1/lisp/org" close to head of `load-path'
(require 'org)

;;;  init.el ends here
```

**Comment by raxod502** [comment] 2019-09-14 16:40
Thanks for the reports everyone. The issue should now be fixed :)

**Comment by Wetlize** [comment] 2019-09-18 05:29
Hi @raxod502, I've just tried your new update with the previously published repro.
After downloading everything and executing `org-version` (without restarting Emacs) it prints:

> Org mode version 9.2.6 (release_9.2.6-538-g23113f @ /home/.../.emacs.clear.build/straight/build/org-plus-contrib/)

After restart it prints:

> Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /home/.../.emacs.clear.build/straight/build/org-plus-contrib/)

If you attempt to remove in-build `org` from `load-path` before loading straight's `org` it emits the next error: 

> File is missing: Cannot open load file, No such file or directory, org-version.el

Is `org-version` just prints bogus output and it still loads the newest version? Can I verify this somehow? I'm using Emacs 26.1, but I don't think this should cause any issues?

**Comment by raxod502** [comment] 2019-09-18 16:21
> everything works as intended

Does it? I believe that if `straight-fix-org` is non-nil, then `straight.el` should define its own `org-version` that works correctly. That previously didn't happen unless Org was rebuilt, which is what I just fixed. It sounds like you're still seeing that behavior, though?

**Comment by Wetlize** [comment] 2019-09-18 17:57
Well, [the mentioned commit](https://code.orgmode.org/bzg/org-mode/commit/1fd07c1eeb0f29de9ce058fac995031413201d4d) makes changes in `org.el` file and I successfully received these changes, so here goes that.

I have only limited time to dig deeper into the rabbit hole, but it looks like what happening is straight uses in-build `org-version`[1] instead of the version from `straight--fix-org-function`. This also explains why I am getting the error when I remove the in-build version of `org` from the `load-path`.

Other than that, straight actually loads the latest version of org-mode as intended. Maybe you should just write an `:override` advice for functions from `org-release` for time being?

[1] this where function definition of `org-release` points to; additionally `find-library` point to in-built `org-version`.

**Comment by raxod502** [comment] 2019-09-19 15:22
@Wetlize I tested again with the following init-file:

```elisp
(setq straight-repository-branch "developh")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'org-plus-contrib)

(require 'org)
```

Running `M-x org-version` returns the correct value (9.2.6) both initially and after a restart. I suspect that either you are not running the latest `straight.el` or there is something else in your configuration (such as code run before `(straight-use-package 'org)` that causes Org to be loaded) that is causing the problem.

**Comment by piotr-yuxuan** [comment] 2019-11-21 23:33
@Wetlize Have you tried to make sure no version of `org` is installed by `packages.el`, then update the state of straight.el itself?
``` elisp
straight-pull-all
straight-rebuild-all
straight-freeze-versions
```
With my `init.el` containing exactly:
``` elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'org-plus-contrib)

(require 'org)
```
After uninstalling custom org versions and updating `straight.el` I got the correct behaviour I want.

**Comment by minikN** [comment] 2019-12-17 12:36
> @Wetlize Have you tried to make sure no version of `org` is installed by `packages.el`, then update the state of straight.el itself?
> 
> ```emacs-lisp
> straight-pull-all
> straight-rebuild-all
> straight-freeze-versions
> ```
> 
> With my `init.el` containing exactly:
> 
> ```emacs-lisp
> (defvar bootstrap-version)
> (let ((bootstrap-file
>        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
>       (bootstrap-version 5))
>   (unless (file-exists-p bootstrap-file)
>     (with-current-buffer
>         (url-retrieve-synchronously
>          "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
>          'silent 'inhibit-cookies)
>       (goto-char (point-max))
>       (eval-print-last-sexp)))
>   (load bootstrap-file nil 'nomessage))
> (straight-use-package 'use-package)
> (straight-use-package 'org-plus-contrib)
> 
> (use-package org)
> ```
> 
> After uninstalling custom org versions and updating `straight.el` I got the correct behaviour I want.

I'm doing exactly the same thing. After the inital start I get `org-version`: 9.3. After a restart however it's back to 9.1.9....

**Comment by raxod502** [comment] 2019-12-17 18:14
@minikN the problem is only fixed on `develop`

```elisp
(setq straight-repository-branch "develop")
```

**Comment by raxod502** [comment] 2020-03-16 18:31
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and the thread may be reopened :)

**Closed by raxod502** 2020-03-16 18:31 UTC
Labels: bug, build system, fixed on develop, org-mode, waiting on response

**Comment by azzamsa** [comment] 2020-07-14 12:17
I've the same issue with org mode and org-plus-contrib. Installed straight.el for more than a month, but hesitate to open the issue cause still don't have time to reproduce with clean env.

I've read many issue about org-mode here, and mimicking other people org-mode config with straight.el, noting works. I need to restart my emacs for 3 times every time I boot my laptop. it's quit annoying for month, otherwise org-mode doesn't work and throws lot of errors such `Error running timer ‘org-indent-initialize-agent’: (void-function org-time-add)` or `org-archive-subtree: Symbol’s function definition is void: org-show-all`.

Fortunately I try to re-search any issue about org and found this one today.

**solved** by adding `(setq straight-repository-branch "develop")` and `(straight-use-package 'org-plus-contrib)` in the head of my init file.

Thanks for straight.el
