### ISSUE TITLE
elfeed-org gets "No such file or directory" when using straight.el

### ISSUE THREAD

**Issue by kalq** [raxod502/straight.el#474] opened 2020-02-08 20:36 UTC
I'm using straight.el with use-package integration. All my packages work fine except [elfeed-org](https://github.com/remyhonig/elfeed-org). This is the error I get:

`(file-missing "Cannot open load file" "No such file or directory" "s")`

when trying to evaluate:

`(use-package elfeed-org
    :ensure t)`

 It works fine using just package.el from melpa. I'm new to straigh.el and my elisp skills aren't as good as I'd like so I'm not sure what needs to be done to fix this.

**Comment by raxod502** [comment] 2020-02-09 21:32
You are instructing `use-package` to invoke `package.el`, not `straight.el`. Use the `:straight` keyword, not `:ensure`.

**Comment by kalq** [comment] 2020-02-09 22:13
Apologies that was a typo. I do have it as `:straight t`. I'm too used to the `:ensure t` from years of just using `package.el`.

The error is the same. Here's the full debug:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "s")
  require(s)
  eval-buffer(#<buffer  *load*-119572> nil "/home/bassam/.emacs.d/straight/build/elfeed-org/elfeed-org.el" nil t)  ; Reading at buffer position 1603
  load-with-code-conversion("/home/bassam/.emacs.d/straight/build/elfeed-org/elfeed-org.el" "/home/bassam/.emacs.d/straight/build/elfeed-org/elfeed-org.el" t t)
  require(elfeed-org nil t)
  (not (require (quote elfeed-org) nil t))
  (if (not (require (quote elfeed-org) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote elfeed-org)) :error))
  (condition-case err (if (not (require (quote elfeed-org) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote elfeed-org)) :error)) ((debug error) (funcall use-package--warning21 :catch err)))
  eval-buffer(#<buffer  *load*> nil "/home/bassam/.emacs.d/init.el" nil t)  ; Reading at buffer position 2819
  load-with-code-conversion("/home/bassam/.emacs.d/init.el" "/home/bassam/.emacs.d/init.el" t t)
  load("/home/bassam/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1df6a1>)()
  command-line()
  normal-top-level()
````

**Comment by raxod502** [comment] 2020-02-10 18:30
It's elfeed-org's fault for using a nonstandard Package-Requires header which could not be parsed by `straight.el`. I added a workaround to `straight.el`, so the problem should be fixed now. Thanks for the report!

**Comment by raxod502** [comment] 2020-02-10 18:31
When testing, make sure to switch to the `develop` branch of `straight.el`,

```elisp
(setq straight-repository-branch "develop")
```

**Comment by kalq** [comment] 2020-02-10 22:10
It seems to work for elfeed-org but when I did a fresh setup with both the `develop` and `master` branches, using the `develop `branch makes it so that a bunch of the required package dependencies are not automatically downloaded and built. I have to manually include them in my config. Whereas with the `master` branch, I only have to manually include the `s.el` package to get elfeed-org working:

`(use-package s :straight t)`

For the `develop` branch, I need to manually include `bind-key` for all my `use-package` declarations that use `:bind`. In addition I need to manually include:

- `dash` for `flycheck`
- `ivy` and `swiper` for `counsel`
- `jsonrpc` for `eglot`

**Comment by ztlevi** [comment] 2020-02-12 01:10
I have similar issue here. `dap-mode` installed by straight.el has missing `pfuture` lib. And `youdao-dictionary` has missing `chinese-word-at-point` lib. 

It's a bit difficult for me to reproduce the issue with vanilla Emacs since I'm using Doom. But I can put some instructions from vanilla doom if u like...

Here is my setup info:
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2
        build      Dec 23, 2019
        buildopts  (--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro')
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD abbfea8 2020-02-11 14:15:36 -0500
        dir        ~/.doom.d/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 4.15.0-76-generic #86~16.04.1-Ubuntu SMP Mon Jan 20 11:02:50 UTC 2020 x86_64
        path       (~/.conda/envs/av/bin/ ~/av/argo/scripts ~/python/bin ~/.local/share/tmuxifier/bin /usr/local/opt/emacs-mac/bin ~/.emacs.d/bin ~/.local/share/pyenv/shims ~/.local/share/pyenv/bin ~/anaconda3/bin ~/.local/share/nodenv/shims ~/.local/share/nodenv/bin ~/.local/share/nodenv/versions/12.10.0/bin /usr/lib/jvm/java-12-oracle/bin ~/.local/share/android/bin ~/.local/share/go/bin /usr/local/cuda/bin /home/linuxbrew/.linuxbrew/bin ~/.nix-profile/bin ~/.local/bin ~/Dotfiles/bin ~/.local/share/Dotfiles/desktop.bspwm.topic/bin ~/.local/share/Dotfiles/editor.emacs.topic/bin ~/.local/share/Dotfiles/misc.apps.topic/bin ~/.local/share/Dotfiles/shell.git.topic/bin ~/.local/share/Dotfiles/shell.tmux.topic/bin ~/av/argo/scripts ~/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin /usr/lib/jvm/java-12-oracle/db/bin ~/.aws/bin ~/.antigen/bundles/robbyrussell/oh-my-zsh/lib ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/github ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-extras ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitignore ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitfast ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-machine ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/ruby ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rbenv ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pipenv ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/django ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/golang ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/node ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/yarn ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/react-native ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/zsh_reload ~/.antigen/bundles/zsh-users/zsh-completions ~/.antigen/bundles/zsh-users/zsh-syntax-highlighting ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux-cssh ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmuxinator ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/aws ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fzf ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/jira ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/ripgrep ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/web-search ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/nmap ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/copydir ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/common-aliases ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/colored-man-pages ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rsync ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/dotenv ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fasd ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fd ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/extract ~/.antigen/bundles/soimort/you-get ~/.antigen/bundles/denysdovhan/spaceship-prompt ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/ubuntu ~/av/argo/tools/hub-linux-amd64-2.3.0-pre8/bin ~/av/argo/tools/hub-linux-amd64-2.3.0-pre8/bin /usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu/)
config  envfile    envvar-file
        elc-files  0
        modules    (:completion (company +auto) (ivy +icons +prescient +childframe) :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) lispy multiple-cursors rotate-text snippets :emacs (dired +ranger +icons) electric ibuffer vc :term eshell vterm :checkers (syntax +childframe) spell grammar :tools debugger direnv docker editorconfig eval (lookup +devdocs +docsets) lsp macos magit make pdf prodigy rgb tmux upload :lang (cc +lsp) data emacs-lisp (go +lsp) (java +lsp) javascript kotlin latex (markdown +grip) nix (org +dragndrop ipython +pandoc +pomodoro +present) (python +pyenv +conda +lsp) rust sh web :config (default +bindings +snippets +smartparens))
        packages   ((helm) (dired-narrow) (edit-indirect) (atomic-chrome) (link-hint) (symbol-overlay) (tldr) (blog-admin :recipe (:host github :repo codefalling/blog-admin)) (chinese-word-at-point) (youdao-dictionary) (wucuo) (org-wild-notifier) (vterm-toggle :recipe (:host github :repo jixiuf/vterm-toggle)) (counsel-etags) (imenu-list) (bazel-mode :recipe (:host github :repo bazelbuild/emacs-bazel-mode)) (import-js) (importmagic) (py-isort) (lsp-treemacs) (flycheck-mypy) (flycheck-google-cpplint :recipe (:host github :repo flycheck/flycheck-google-cpplint)) (lsp-treemacs))
        elpa       (pfuture)
        unpin      (n/a)
```
</details>

**Comment by raxod502** [comment] 2020-02-12 19:33
Try again now that I've fixed the problem where I accidentally made the entire dependency management system nonfunctional for everyone (https://github.com/raxod502/straight.el/issues/476).

**Comment by kalq** [comment] 2020-02-12 22:31
Everything works. Thanks so much for your work!

**Comment by ztlevi** [comment] 2020-02-12 23:06
Looks good now. Thanks

**Closed** 2020-02-13 16:17 UTC
Labels: bug, external bug, nonstandard packaging, use-package, ಠ_ಠ
