### ISSUE TITLE
straight.elc in repo

### ISSUE THREAD

**Issue by xenodasein** [raxod502/straight.el#897] opened 2021-12-06 21:20 UTC
After my first bootstrap I noticed there is a straight.elc file not only in build directory but also in git repo; is this something strictly necessary or an oversight as it seems to violate guiding principles apart from being subjectively a messy functionality?

**Comment by progfolio** [comment] 2021-12-07 23:57
I believe this happens during the bootstrapping process. The file isn't needed after that, but it shouldn't cause any harm.
How do you suppose it violates the guiding principles?

**Comment by xenodasein** [comment] 2021-12-08 10:34
If it is not needed please delete it. Copying the repository might break reproducibility. I don't know man, the project has strong opinions about doing things right, built in package system modifying custom-file is explained as devils work; least I expect is that straight.el shouldn't litter around with .elc files.

**Comment by progfolio** [comment] 2021-12-08 21:35
> I don't know man, the project has strong opinions about doing things right, built in package system modifying custom-file is explained as devils work; the least I expect of straight.el is not to be littering around with .elc files.

Please don't be combative. I help maintain this package in my spare time, but I didn't write the initial README.
The opinions of the original author aren't necessarily mine.

> Copying the repository to another system might break reproducibility.

Can you  explain any scenarios where this would happen? I'm trying to understand the risk and how likely it is.
This will help me prioritize this issue. Thank you.

**Comment by progfolio** [comment] 2021-12-08 21:53
Here's a recipe you should be able to use to remove the elc file after straight bootstraps:

```emacs-lisp
(straight-use-package 'straight :post-build (let ((default-directory (straight--repos-dir "straight.el")))
                                              (when (file-exists-p "straight.elc")
                                                (delete-file "straight.elc"))))
```

Confirmed with the following:

<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "elc-test"
  :preserve t
  :pre-bootstrap 
  (setq straight-repository-branch "develop")
  :post-bootstrap 
  (straight-use-package 'straight :post-build
                        (let
                            ((default-directory
                              (straight--repos-dir "straight.el")))
                          (when
                              (file-exists-p "straight.elc")
                            (delete-file "straight.elc"))
                          (message "%s"
                                   (shell-command-to-string "ls -lah")))))
```
</details>

- Test run at: `2021-12-08 16:50:28`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 92d4153 2021-11-23`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars)
 of 2021-12-03`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Rebuilding all packages due to build cache schema change
Looking for gnu-elpa-mirror recipe -> Cloning melpa...
Looking for gnu-elpa-mirror recipe -> Cloning melpa...done
Looking for emacsmirror-mirror recipe -> Cloning gnu-elpa-mirror...
Looking for emacsmirror-mirror recipe -> Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe -> Cloning el-get...
Looking for emacsmirror-mirror recipe -> Cloning el-get...done
Looking for straight recipe -> Cloning emacsmirror-mirror...
Looking for straight recipe -> Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 92d4153 2021-11-23
total 532K
drwxr-xr-x 9 n n  420 Dec  8 16:50 .
drwxr-xr-x 7 n n  140 Dec  8 16:50 ..
drwxr-xr-x 2 n n   60 Dec  8 16:50 .circleci
-rw-r--r-- 1 n n   72 Dec  8 16:50 .dir-locals.el
drwxr-xr-x 8 n n  260 Dec  8 16:50 .git
drwxr-xr-x 3 n n   80 Dec  8 16:50 .github
-rw-r--r-- 1 n n   52 Dec  8 16:50 .gitignore
-rw-r--r-- 1 n n  169 Dec  8 16:50 Dockerfile
-rw-r--r-- 1 n n 1.1K Dec  8 16:50 LICENSE.md
-rw-r--r-- 1 n n 3.3K Dec  8 16:50 Makefile
-rw-r--r-- 1 n n 158K Dec  8 16:50 README.md
drwxr-xr-x 2 n n   60 Dec  8 16:50 benchmark
-rw-r--r-- 1 n n 5.7K Dec  8 16:50 bootstrap.el
-rw-r--r-- 1 n n  303 Dec  8 16:50 indent.el
-rw-r--r-- 1 n n  13K Dec  8 16:50 install.el
drwxr-xr-x 2 n n  120 Dec  8 16:50 scripts
-rw-r--r-- 1 n n  525 Dec  8 16:50 straight-ert-print-hack.el
-rw-r--r-- 1 n n 7.6K Dec  8 16:50 straight-x.el
-rw-r--r-- 1 n n 311K Dec  8 16:50 straight.el
drwxr-xr-x 3 n n   80 Dec  8 16:50 tests
drwxr-xr-x 2 n n  140 Dec  8 16:50 watcher

Packages:
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 08bc6d7e 2021-12-05
"gnu-elpa-mirror"         n/a                  master 98cfebc 2021-11-30
"el-get"                  melpa                master 960f3fb9 2021-10-31
"emacsmirror-mirror"      n/a                  master e828d51 2021-12-03
"straight"                n/a                  develop 92d4153 2021-11-23


```
</details>

That should help mitigate the issue between now and when I look into it. Does that help?

**Comment by xenodasein** [comment] 2021-12-09 11:56
> Please don't be combative. I help maintain this package in my spare time, but I didn't write the initial README. The opinions of the original author aren't necessarily mine.

Sorry if that sounded rude, definitely not directed against you, I said it facing the README.md and it's tone. Your help is much appreciated.

> > Copying the repository to another system might break reproducibility.
> 
> Can you explain any scenarios where this would happen? I'm trying to understand the risk and how likely it is. This will help me prioritize this issue. Thank you.

I was planning to reuse the 'repos' directory, by symlinking it on other systems and not to not clone the repos every time. My knowledge is anecdotal as to how copying elc files to different systems cause problems, but I remember it was advised against.

Thank you for the post-build solution, I will be using it. It is probably better for it to be solved in bootstrap code sometime but of course this is not something high priority, it could wait in project TODO list. Thanks for your time.

**Comment by progfolio** [comment] 2021-12-09 19:12
> I was planning to reuse the 'repos' directory, by symlinking it on other systems and not to not clone the repos every time. My knowledge is anecdotal as to how copying elc files to different systems cause problems, but I remember it was advised against.

I see. Well you would only run the risk of that `elc` being loaded if you were to manually put the repo directory in your `load-path`. Straight does not do that. It puts the `build` directory in the `load-path`. 

In general, you can run into trouble if the `elc` file was generated with one version of Emacs and then loaded with another. This is not guaranteed to work because byte-code compatibility is not guaranteed across Emacs versions. So even in the case of the `elc` files in the `build` directory, you would want to rebuild them per Emacs/system change.

Given we have a workaround and a relatively uncommon use-case/low risk here, I'm going to close this issue for now.
Your concerns are noted and I will look into them in the future. Thanks.

**Comment by xenodasein** [comment] 2021-12-12 13:04
> I see. Well you would only run the risk of that `elc` being loaded if you were to manually put the repo directory in your `load-path`. Straight does not do that. It puts the `build` directory in the `load-path`.

But that's even worse; WHY then is it littering the repo? (I don't care, it just shouldn't.)

> In general, you can run into trouble if the `elc` file was generated with one version of Emacs and then loaded with another. This is not guaranteed to work because byte-code compatibility is not guaranteed across Emacs versions. So even in the case of the `elc` files in the `build` directory, you would want to rebuild them per Emacs/system change.

Probably neither I nor you know all the intrinsic details of emacs byte-code compatibility. The point is, we shouldn't need to know that, if things are done properly.

> Given we have a workaround and a relatively uncommon use-case/low risk here, I'm going to close this issue for now. Your concerns are noted and I will look into them in the future. Thanks.

It'd be better if this stays open until fixed or noted to milestone. Thank you but you didn't concoct the system that cause this I'm guessing so it need not be your responsibility. This may look like bike-shedding but so does the raison d'être of straight.el's origin, thus I reserve my right.

**Comment by progfolio** [comment] 2021-12-12 16:13
I've re-opened the issue for you. Please work on your tone when requesting help.

Apologies that the workaround I suggested not working for you. In that case, I recommend leaving the `elc` file where it is unless it's causing you a concrete problem. I won't be looking into this issue any time soon. In part because of your attitude, but mostly because no concrete issue has been brought to light. If you would like to look into it more and prepare a pull request, patches are welcome.

**Closed** 2021-12-28 13:33 UTC
Labels: help wanted, needs repro, support
