### ISSUE TITLE
Making different versions of emacs cohabitate

### ISSUE THREAD

**Issue by ThibautVerron** [raxod502/straight.el#484] opened 2020-02-21 12:01 UTC
(Follow-up to https://github.com/raxod502/straight.el/pull/482)

It turns out that having a different "build" directory for each target version is not enough, because the file `build-cache.el` also depends on the emacs version.

An easy fix would be to replace the definition of `straight--build-cache-file` with

```
(defun straight--build-cache-file ()
  "Get the file containing straight.el's build cache."
  (straight--build-file "build-cache.el"))
```

so that the cache itself is in the "build" directory.

But changing it like that would make all installations recompile all their packages when updating straight, is it acceptable?

Otherwise, what would be the best course of action? Making it a setting with the current behavior the default? Or adding some code copying the current cache if it exists?

**Comment by raxod502** [comment] 2020-02-21 17:56
> the cache itself is in the "build" directory.

That sounds reasonable; however, I'd prefer to avoid placing the build cache directly in the `build` directory, because it will then be very hard to find among all the package directories (and, in an edge case, could even conflict with a package called `cache.el`).

What about simply adding a user option analogous to `straight-build-dir`, called `straight-build-cache-file`? Then if you wish to enable version isolation, you can set both of those variables. We can later add a feature to `straight.el` to do this automatically if it proves a popular use case.

> changing it like that would make all installations recompile all their packages when updating straight, is it acceptable?

With my proposed course of action above, there wouldn't be any migration necessary. However, since you asked, my general policy is to not worry about migration code, as it quickly gets very complicated for a relatively high-velocity project such as `straight.el`. There are many reasons the build cache might need to get rebuilt (check [`straight--load-build-cache`](https://github.com/raxod502/straight.el/blob/ed54b626b0faec36fdaff30c72351d5fb41a6786/straight.el#L3286-L3321)), and in all of them we just chuck it out and start over, even if the case could be handled by a migration.

**Comment by ThibautVerron** [comment] 2020-02-21 18:07
> That sounds reasonable; however, I'd prefer to avoid placing the build cache directly in the build directory, because it will then be very hard to find among all the package directories (and, in an edge case, could even conflict with a package called cache.el).

That's a very good point. 

> What about simply adding a user option analogous to straight-build-dir, called straight-build-cache-file? Then if you wish to enable version isolation, you can set both of those variables. We can later add a feature to straight.el to do this automatically if it proves a popular use case.

Another possibility, without placing the cache file in the build directory, would be to create the name of the cache file based on the name of the build directory. 

I understand that there are very good reasons not to place the cache file in the build directory, but the cache file is still intrinsically connected to the results of the build, right? 

But it would make the `straight--build-dir` variable more obscure.

> With my proposed course of action above, there wouldn't be any migration necessary.

Yes, that's quite clearly the easiest way.

> However, since you asked, my general policy is to not worry about migration code, as it quickly gets very complicated for a relatively high-velocity project such as straight.el. There are many reasons the build cache might need to get rebuilt (check straight--load-build-cache), and in all of them we just chuck it out and start over, even if the case could be handled by a migration.

I suspected so, otherwise I wouldn't even have asked.

Should I make a pull request, or is it more work for you than adding the 3 necessary lines?

**Comment by raxod502** [comment] 2020-02-21 18:11
> the cache file is still intrinsically connected to the results of the build, right?

Right.

> Another possibility

How about the following middle ground: we make the `build-cache-file` variable default to `build-cache.el`, and in `straight--build-cache-file`, we expand it relative to the _parent_ of `straight--build-dir`. This way it is possible for the user to specify their own path if necessary, but it works as expected by default.

> Should I make a pull request

I would prefer this, thanks for asking.

**Comment by ThibautVerron** [comment] 2020-02-21 18:21
I'm not sure if I understand... isn't the parent of `straight--build-dir` always `(straight--base-dir)/straight`?

**Comment by raxod502** [comment] 2020-02-22 19:54
No, not necessarily if the user has customized `straight-build-dir`.

**Comment by raxod502** [comment] 2020-02-22 19:58
Okay. Now that I thought about it again, my proposal doesn't actually solve the problem that you pointed out. So we shouldn't do like I suggested. I think the best option would be what you proposed, which is to make the default value of `straight-build-cache-file` nil, and then at runtime if it's nil then expand it to `(straight--build-file)` concatenated with `-cache.el`. Otherwise expand it as `(straight--file straight-build-cache-file)`.

**Comment by ThibautVerron** [comment] 2020-03-11 12:25
It appears that this setting (and the previous one for the build directory) is not applied when bootstrapping `straight`.

The variables are passed to the bootstrapping process in the `/tmp/straight.el~...` file alright, but the rest of the code is pulled from the `install/alpha` branch which does not use them.

I don't pretend to be understanding everything from the boostrapping process, and in particular the design choice between all those versions, but wouldn't it make sense to shortcut the whole thing and use `"develop"` during bootstrapping  if `straight-repository-branch` is set `"develop"` itself?

**Comment by raxod502** [comment] 2020-03-18 14:55
> It appears that this setting (and the previous one for the build directory) is not applied when bootstrapping straight.

Oops, yes.

> Do you merge both master and install/alpha every time you do a release?

No. I would suggest reading the comments at the top of `install.el` to understand what's going on here. What you need to know is that every time some functionality is changed that would affect the bootstrapping process, the keyword written by `straight-freeze-versions` must be updated, and a new branch must be created called `install/%s`. I forgot to do this, hence the changes not propagating.

> In any case, is it possible to short-circuit the whole thing and use "develop" during bootstrapping if straight-repository-branch is set to "develop" itself?

It would be possible but it would be a bad idea. The reason for this whole system is that I want to support full reproducibility. That means that if you have an old version of `straight.el` in your lockfile, then `straight.el` will be bootstrapped using _that_ version, and not the latest one. Even if you're tracking the `develop` branch. (Otherwise, you'd have no way of properly trying out an old version of your config.) The other issue is stability. I don't want to break the bootstrap for everyone just because I push a bug to `develop`. It should only break for the people who upgrade to the broken commmit.

**Comment by ThibautVerron** [comment] 2020-03-19 15:01
I see, sorry for making you write that explanation.

It still sounds to me like it's duplicating something that would be doable with standard git features (maybe having the bootstrapper pull from a given commit?), but you definitely put more thought into it than I did, and I am a firm believer in not fixing what's not broken.

Following the instructions in those comments, when I find the time (weirdly enough, I find myself with _less_ time now that I'm locked home), I will make a PR making sure the new variables are safeguarded with `bound-and-true-p`.

**Comment by raxod502** [comment] 2020-03-21 15:52
> It still sounds to me like it's duplicating something that would be doable with standard git features (maybe having the bootstrapper pull from a given commit?)

This does seem like a possibility. I spent a few minutes thinking about it, and one issue that would arise is that different versions of `straight.el` may have different ways of interpreting a recipe that would lead to different names for the local repository used for `straight.el`. That would make the commit show up in a different place in the lockfile. There may indeed be a way to make a simplifying assumption or two, and get rid of all of this...

> I am a firm believer in not fixing what's not broken.

... but, yeah -- at least, for now. The main issue when I (or others) forget to update the lockfile version schema, and therefore new bootstraps don't get to take advantage of added features. It would be worth putting in some work to solving that problem, but probably not today.

> I will make a PR making sure the new variables are safeguarded

I don't think this should be necessary, unless there is a pretty bad bug. Where are you looking in the code?

**Comment by progfolio** [comment] 2021-09-25 22:39
@ThibautVerron: Any interest in working on this feature?

**Comment by ThibautVerron** [comment] 2021-09-26 20:28
I must confess that I had forgotten about this thread. I opted for symlinking the build folder out of the "shared between computers" folder a while back, but on my current computer, I recently installed the development branch of emacs in addition to the official emacs27 package, and I didn't have to think about straight.

Do you have specific problems?

In case it's helpful, here is the relevant code in my [init.el](https://gitlab.com/thibaut.verron/dot-emacs/-/blob/master/init.el):

```
(defconst tv/system-type (replace-regexp-in-string "/" "-" (format "%s" system-type)))
(defconst tv/system-string (concat tv/system-type "-" emacs-version))

(setq straight-use-package-by-default t  
      straight-recipes-gnu-elpa-use-mirror t
      straight-build-dir (expand-file-name
			  (concat "build" "-" tv/system-string)
			  tv/user-local-emacs-directory)
      straight-repository-branch "develop")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el"
	       user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
```

**Comment by progfolio** [comment] 2021-09-26 21:32
> Do you have specific problems?

No. I was just curious if you were still interested in this feature.
Seeing as it hasn't been requested by anyone else, I think we'll opt to close this issue for now.

**Closed by progfolio** 2021-09-26 21:32 UTC
Labels: feature, build system, build cache, multiple versions, user option
