### ISSUE TITLE
Issues with new native-comp support

### ISSUE THREAD

**Issue by alphapapa** [raxod502/straight.el#511] opened 2020-04-24 07:56 UTC
As I mentioned in comments on https://github.com/raxod502/straight.el/pull/507, the changes merged there are somewhat inadvisable.

* It makes no sense to block while native compilation happens.  That defeats the purpose of the asynchronous compilation that Andrea has implemented.  It means minutes of waiting while Emacs is blocked for no good reason.
* A few minor improvements to `comp.el` would support the desired behavior in which packages would be compiled at install-time (rather than deferring compilation until load-time), while not forcing packages to be loaded when compilation finishes (unless the user has already loaded their byte-compiled forms while waiting for native compilation).
* As well, adding code for this may be premature, because symbols may be renamed at any time.  I already contributed a patch to `comp.el` that renamed some, and some other symbols, including some referenced in that PR, should also be renamed for clarity and consistency.  I would expect such renaming and refactoring to take place at least a few times before the branch is merged.

So I would generally recommend that we make the necessary, minor improvements to `comp.el` to support this use case (which would also benefit `package.el`), and that Straight should refrain from adding references to `comp.el` symbols until it is merged to Emacs `master`.

**Comment by alphapapa** [comment] 2020-04-24 07:57
I did not intend for this to be labeled `bug`, but that seems to have happened automatically, and I can't change it.

**Comment by gagbo** [comment] 2020-04-24 12:22
I don't totally understand the issue here. Is it not okay if straight provides a handle to compile AOT ?

I mean, *as a user of straight.el* you can also pass the `:no-native-compile` flag in the recipe, and then enable deferred compilation in order to enjoy asynchronous compilation happening as provided in `comp.el`if I understand #507 correctly

**Comment by flatwhatson** [comment] 2020-04-24 12:39
Blocking until compilation has finished is *optional*, though I'll grant that the API is currently awkward.  Setting `straight--wait-for-async-jobs` to `nil` will completely prevent blocking.  I agree that blocking might not be desirable in the common case, so maybe this should be the default?

I added blocking because I call straight from a command-line process so that package installation *never* impacts my regular use of emacs.  Without blocking, this process exits immediately and nothing is compiled.

As for depending on work-in-progress APIs, I think if there is breakage here it will only affect people who are a) using a bleeding-edge build of emacs and b) using the develop branch of straight.  These crazy folks deserve any breakage!

**Comment by alphapapa** [comment] 2020-04-25 00:37
> I don't totally understand the issue here. Is it not okay if straight provides a handle to compile AOT ?

I don't understand why it seems so hard to communicate about this issue.  I've explained it several times.  Rather than explaining it for a 4th time, I refer you to my previous comments.

> I added blocking because I call straight from a command-line process so that package installation never impacts my regular use of emacs. Without blocking, this process exits immediately and nothing is compiled.

That makes sense for batch mode, but not interactive mode.

> As for depending on work-in-progress APIs, I think if there is breakage here it will only affect people who are a) using a bleeding-edge build of emacs and b) using the develop branch of straight. These crazy folks deserve any breakage!

I don't think anyone deserves breakage.  I think code that is likely to break shouldn't be committed.  Instead of doing that, as I've said 3 times, we should upstream necessary enhancements to `comp.el` so there won't be any breakage.

@raxod502 I don't even use Straight.  I happened to see this PR on GitHub, and since I've been corresponding with Andrea and contributing to `comp.el`, I thought I would offer some suggestions that seem useful, to try to save you and Straight users some trouble.  For some reason, communication about these issues seems extremely difficult, so I give up.  I hope _you'll_ be able to understand what I mean, and then you can make whatever decision is best for Straight.

**Comment by yantar92** [comment] 2020-04-25 07:12
As a user of native-comp branch, I confirm here that this change was surprising. I though that the breakage was in comp.el, not in straight.el. Now, after accidently finding this thread, I finally understand what is going on and why emacs hangs on startup suddenly. 

I believe that default `nil` value for `straight--wait-for-async-jobs` would be better for general use.

**Comment by flatwhatson** [comment] 2020-04-25 11:07
After some consideration I'm convinced that it's best to remove support for blocking for native compilation from `straight.el`.  In standard usage it's better to not block, and removal of the code related to the async compilation queue should address @alphapapa's concerns about our API exposure.

**Comment by flatwhatson** [comment] 2020-04-25 12:40
Reading through the implementation, I've finally understood your point about late loading @alphapapa.  Sincerest apologies that this has taken so long to sink in, and thanks for pointing it out and offering to help.

To re-iterate, the scenario in question goes like this:

 0. Byte-compile "foo.el"
 1. Start async compilation of "foo.el" manually
 2. Load "foo.elc" (possibly triggering deferred compilation)
 3. Finish async compilation (hopefully loading the native forms)

When `comp-deferred-compilation` is set, this actually works as expected.  Our original call to `native-compile-async` requests `'late` loading, and deferred compilation does the same.  The redundant entries to the compilation queue are ignored, but the functions are all added to `comp-deferred-pending-h` which marks them for native replacement.

When `comp-deferred-compilation` is nil, the functions are not added to `comp-deferred-pending-h` so the native forms are not loaded until Emacs is restarted.  This is the case which could be better-supported by `comp.el`.

Are you planning to address this upstream, or would you rather I raise it on the bug tracker?

**Comment by raxod502** [comment] 2020-04-27 15:01
> For some reason, communication about these issues seems extremely difficult, so I give up. I hope you'll be able to understand what I mean, and then you can make whatever decision is best for Straight.

Please be nice, we are all trying our best.

But I think what you suggest is reasonable and I believe the problem is solved by https://github.com/raxod502/straight.el/pull/512. Compilation is now unconditionally asynchronous and started automatically by `straight.el` at installation time.

**Comment by AndreaCorallo** [comment] 2020-05-18 21:07
Hi all,

I discovered you guys have a branch supporting `native-comp', this is just amazing!!

I've been signaled a problem using native-comp with deferred-compilation for compiling org.

I discussed what is my understanding of the situation here 

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=40838#29

and added a customize that I think should help into propagating the org hack into the async workers.

I just wanted to make you aware of this, thanks!

 Andrea

**Comment by andreyorst** [comment] 2020-06-29 18:14
Can we also add `eln-*` to `.gitignore`?

Each time I update all packages I have to press <kbd>d</kbd> to delete this directory from `straight` repo, as `straight` thinks that there are modifications in the source tree. I see that `*.elc` is there, so it makes sense to ignore results of native compilation as well.

**Comment by raxod502** [comment] 2020-07-10 14:12
Done.

**Comment by kadircancetin** [comment] 2020-08-30 20:25
Org roam has unstable under native compile. It used before last native compile branch with `:no-native-compile t` but is not working on last version which build caches under `/eln-cache`. 

Installed source on archlinux: https://aur.archlinux.org/packages/emacs-native-comp-git/
I think the update 11 is broke it: http://akrl.sdf.org/gccemacs.html#org4b11ea1
```
(use-package org-roam
  :straight ( :no-native-compile t ))
```

**Comment by raxod502** [comment] 2020-08-31 13:03
So what you're saying is enabling regular byte-compilation automatically enables native compilation as well, even if you've explicitly disabled native compilation? That would most certainly be a bug, if so.

**Comment by kadircancetin** [comment] 2020-08-31 16:05
Oh, I actually said that but after digging the problem I think it is `comp-deferred-compilation` true by default after [update 11](http://akrl.sdf.org/gccemacs.html#org4b11ea1).

```
comp-deferred-compilation is a variable defined in ‘C source code’.

Documentation:
If non-nil compile asyncronously all .elc files
being loaded.

Once compilation happened each function definition is updated to the
native compiled one.

```

I think it is not about straight to fix it but it will be good on the documentation. After setting the `comp-deferred-compilation` to nil, the problem solved.

**Comment by flatwhatson** [comment] 2020-08-31 22:55
Yes unfortunately `comp-deferred-compilation` won't respect straight's `:no-native-compile` feature, and with deferred compilation now enabled by default it's now "broken" out-of-the-box.

We can prevent deferred compilation for particular files by adding appropriate patterns to `comp-deferred-compilation-black-list`, perhaps this should happen automatically for `:no-native-compile` packages?

**Comment by flatwhatson** [comment] 2020-09-01 11:08
I've proposed #569 to automatically blacklist `:no-native-compile` packages from deferred compilation.

**Comment by raxod502** [comment] 2020-09-16 13:36
After a delay, sorry about that, I've merged the linked pull request. Does that fix this issue?

**Comment by kadircancetin** [comment] 2020-09-20 08:42
Sorry about my delayed response, I have moved emacs 27 so I have needed to recompile `native-comp-branch` and try. 

Today I tried and it seems the problem is fixed on `develop` branch. Very thanks @flatwhatson and @raxod502. Even if there are [so few people](https://github.com/search?p=1&q=%3Ano-native-compile&type=Code) use it, your hardworks make the straight best package manager.

**Comment by raxod502** [comment] 2020-09-21 01:46
Are there further issues to be resolved regarding native compilation, or should this issue be closed?

**Comment by flatwhatson** [comment] 2020-09-21 02:44
I'm not aware of anything outstanding.  Anything else should be raised as a separate issue.

**Comment by raxod502** [comment] 2020-09-21 02:45
Nice :sparkles:

**Closed by raxod502** 2020-09-21 02:45 UTC
Labels: build system, byte compilation, discussion, emacs 28, waiting on response
